### PR TITLE
Dev-->Master v5.2.0

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:squirrel: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Updated company revenue data to 2018
- Updated revenue detail table for improved functionality
- Updated renewables content
- Added revenue trends section
- Added Native American production data to homepage production charts
- Updated monthly production data (now through January 2019)
- Updated monthly revenue data (now through April 2019)

### CODE REVIEW

**Comment by mcharg** [comment]
The revenue trend numbers are different in this build than they were in the previous one.

The last PR:
image

This PR:
image

**Comment by brentryanjohnson** [comment]
@mentastc mentioned earlier that the trends section is reading off the file we just updated in another branch today, so that could be it.

**Comment by mcharg** [comment]
There's no bolding on the Leasing and Production headers on the filterable table page with the font change.
image

**Comment by lpgoldstein** [comment]
This is not make or break but may annoy certain users if they change screen dimensions
image

**Comment by brentryanjohnson** [comment]
@mcharg and @lpgoldstein could you create issues for the styling problems you see and assign them to me?

**Comment by mcharg** [comment]
@brentryanjohnson The Revenue by Company link on the Revenue tab is still going to the 2017 page, but should now go to the 2018 page.

**Comment by jennmalcolm** [comment]
I checked the revenue trend numbers against the new data, and they look good.

**Comment by lpgoldstein** [comment]
Renewables content looks good.

**Comment by lpgoldstein** [comment]
Native American production data on the homepage charts looks good.

**Comment by mentastc** [comment]
Revenue trends and monthly revenue data looks good!

**Comment by mentastc** [comment]
Native American production numbers look good

**Comment by mentastc** [comment]
Monthly production numbers look good

**Pull request merged**
