### PR TITLE
[WIP] Reclamation Fund, how it works

### LINKED ISSUE #4852: Write how-it-works content for Reclamation Fund
Our colleague pointed out that we lack supporting content for the Reclamation Fund, while we do have supporting content for other disbursement funds, including LWCF and HPF. We should consider developing content for the Reclamation Fund...it's a content gap.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #4852

[✍️ PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/hiw-reclamation-fund/how-it-works/reclamation-fund/)

Changes proposed in this pull request:

- Adds how-it-works content for Reclamation Fund
- Adds link and summary to how-it-works landing page

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@Maroyafaied Feel free to copy this into a Word document and edit.

**Comment by brentryanjohnson** [comment]
There are some specific data points in this content. I attempted to avoid them, so we could avoid the accompanying maintenance, but I found it necessary to use some data points to convey the discrepancy between revenue and appropriations, along with the balance.

If anyone has ideas about how to convey the disposition of the balance and incoming/outgoing funds _without_ curating individual data points, I welcome them!

**Comment by brentryanjohnson** [comment]
☝️ The reading grade level was just over our goal at 11th grade, so I made a few gentle edits to bring it down to 10.

**Comment by jennmalcolm** [comment]
Should we include bonuses and rentals in this part? 

image

Also, the original section 35 of the act specifies 52.5% to Reclamation fund (unless I'm not getting something), and it really seems to be the 1976 amendment (sec 317/page 110) that specifies 40%. Should we change the reference to section 317?

image

**Comment by jennmalcolm** [comment]
Do we need the last two since they are also within the text? 
image

**Comment by brentryanjohnson** [comment]
> Should we include bonuses and rentals in this part?
> 
> image
> 
> Also, the original section 35 of the act specifies 52.5% to Reclamation fund (unless I'm not getting something), and it really seems to be the 1976 amendment (sec 317/page 110) that specifies 40%. Should we change the reference to section 317?
> 
> image

I included section 35 because it appears to be where Alaska is exempted. The parenthetical is meant to reference "except in Alaska," not the revenue amount. But I can take it out if it's more confusing than helpful.

**Comment by jennmalcolm** [comment]
@brentryanjohnson should we include that law in the end reference section then?

**Pull request merged**
