### PR TITLE
Blog post on homepage rebuild, part 2

### LINKED ISSUE #3440: Write part two of our blog post series on homepage transition
Part two will cover our transition to using GatsbyJS for new feature development, specifically our new homepage.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3440

[:pencil: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/blog-post-home-2/blog/homepage-revamp-part-two/)

Changes proposed in this pull request:

- Adds syntax highlighter package and CSS for blog code blocks
- Adds part two of homepage rebuild post series

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@master12 I added content about the prefetch and `pages.json` problems. Please review.

> ## Integrating with Jekyll
> Related to redundancy, providing a seamless user experience between the Gatsby and Jekyll portions of the site has been a challenge.

> Page routing has been among the more significant challenges, ironically due to a beloved feature in Gatsby: prefetching. Developers tout Gatsby’s speed, and prefetching page assets is integral to Gatsby’s performance advantages. But when we link to a Jekyll page, Gatsby can’t prefetch the assets, and we have to use workarounds to stitch the separate parts of the site together.

> Basically, the Jekyll part of the site deploys to a directory that isn’t known to Gatsby at build time. Consequently, Gatsby creates a pages.json object that contains the wrong location for files. To deal with this, we add front matter to the Gatsby-built pages after they’re compiled and resolve the paths.

**Comment by master12** [comment]
Ok check it out

**Comment by brentryanjohnson** [comment]
I've edited that section, @master12, and pushed it up. Please review.

I omitted the sentence about other developers referencing `onClientEntry`. I'd like to restore that, but I think we should track down the link to the issue, if we're going to reference it.

**Comment by master12** [comment]
@brentryanjohnson Looks good

**Comment by jennmalcolm** [comment]
Looks good. I added a couple of minor suggestions to the Google Doc. That's all I have.

**Comment by brentryanjohnson** [comment]
@mcharg suggested minor modifications to the titles, so that commit is in the current build. When that build is complete, this can probably be merged with one more review by @jennmalcolm.

**Comment by brentryanjohnson** [comment]
Found a typo, @jennmalcolm. One more commit needed.

**Pull request merged**
