### PR TITLE
dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Transitions most How it Works pages to Gatsby
- LWCF Update
- Link fixes
- Updated disbursements visual on explore data back to 2009

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Things to check: 

Navigate between pages
- [ ] Check several types of location profile page to ensure data and liquid templates are working as expected
- [ ] Check links are working correctly
- [ ] Check drop downs menu and validate they work 

Text
- [ ] No misspelling
- [ ] Correct spacing
- [ ] Correct format
- [ ] Accurate dates displayed

Check all browsers
- [ ] Chrome
- [ ] Internet Explorer
- [ ] Safari
- [ ] Firefox
- [ ] Edge

Check all devices
- [ ] Dell Laptop
- [ ] Chromebook
- [ ] Macbook
- [ ] iPad
- [ ] iPhones
- [ ] Samsung phones

Check all responsive breakpoints
- [ ] < 480 px (switches to one-column layout)
- [ ] 600 px (changes bar chart layout from three column to accordion with one column)
- [ ] 768 px (converts side navigation from separate column to the right to a select list)
- [ ] > 768 (full site layout)

**Comment by mcharg** [comment]
Can we get a list of which How It Works pages were converted?

**Comment by jennmalcolm** [comment]
- Fossil Fuels
- Nonenergy Minerals
- Renewables
- Federal Laws and Regulations
- Federal Reforms
- Regulations
- Coal
- Offshore Oil and Gas

**Comment by mcharg** [comment]
This build is taking forever.

**Comment by jennmalcolm** [comment]
Yeah, it says an hour. That is crazy. Seems like something is wrong.

**Comment by jennmalcolm** [comment]
Oh, now it's done.

**Comment by mcharg** [comment]
@master12 On the main How It Works page, the Table of Contents menu is displaying at the bottom between about 400 px and 767 px.

**Comment by mcharg** [comment]
@master12 The header nav is missing from the header on these pages:
- Fossil Fuels
- Nonenergy Minerals
- Renewables
- Federal Laws and Regulations
- Federal reforms
- State laws and regulations

**Comment by master12** [comment]
@mcharg found the issue with the nav its being fixed now hold on

**Comment by master12** [comment]
I changed how we load templates so it broke previous template loads. This should be resolved with the latest commits. Only affects how it works.

**Comment by mcharg** [comment]
LWCF and link fixes look good.  @brentryanjohnson How do we view the content guide?

**Comment by jennmalcolm** [comment]
@mcharg that's on the Wiki. You don't really need to review it. I took it out of the top list.

**Comment by brentryanjohnson** [comment]
Since the content guide is in the wiki, it doesn't ship with the release. We can change it anytime. :)

**Comment by mcharg** [comment]
@master12 Now the table of contents is stuck open on the main How It Works page.

**Comment by mcharg** [comment]
@master12 Now it's not doing it after leaving the page and coming back.

**Comment by mcharg** [comment]
The nav is fixed on the other pages.

**Comment by mcharg** [comment]
Created #3704 and #3705 for two minor issues, one on mobile and one in IE.

**Comment by master12** [comment]
Ok updated some breakpoints for the TOC. Please refresh page when switching between responsive views. On main page the toc sticks only when you switch the responsive view and dont refresh, atleast  thats what I see.

**Comment by brentryanjohnson** [comment]
Active nav item isn't bolded, as it is in production.

## This PR
nav items with how it works not bolded

## Production
nav items with how it works bolded

**Comment by lpgoldstein** [comment]
This link on How it works - fossil fuels - gas
image
 goes to a bad link 
image

will find right link

**Comment by lpgoldstein** [comment]
Under Coal 
image
 doesn't work ---tries to go to a BIA link - not sure where it should go? 
image

**Comment by lpgoldstein** [comment]
Missing periods under "What are Reserves" in how it works? 

image

**Comment by lpgoldstein** [comment]
How it works/Non Energy Minerals/ Explore Production Data link broken

**Pull request merged**
