### PR TITLE
Adds page and subnavigation for monthly production data

### LINKED ISSUE #3363: Create download and docs page for monthly production data
We have a new download and docs page and "tab" pattern for monthly revenue (#3358), but we need one for production as well. We can use a similar pattern to revenue.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3363

[:snake: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/monthly-production/downloads/federal-production/)

Changes proposed in this pull request:

- Adds tab nav include for monthly production data
- Adds page for monthly production data

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
This is in WIP status, because we need to add the data file and documentation for monthly production data. The first commit only adds the structure and "tab" nav.

**Comment by mcharg** [comment]
Looks good.

**Comment by jennmalcolm** [comment]
@brentryanjohnson, you're waiting to co-work with @mentastc on the documentation part of this, right? I'm not sure if will be working again this afternoon, but I could help with it instead if you want. Let me know.

**Comment by brentryanjohnson** [comment]
I worked on this yesterday. If it looks good to you, @jennmalcolm, we can probably include it in the release.

**Pull request merged**
