### PR TITLE
Removes site.baseurl path variable from state markdown files

### LINKED ISSUE #3521: Fix links generated by site.baseurl variable
In our transition to GatsbyJS, we haven't refactored many of the `{{ site.baseurl }}` links. Consequently, we have broken internal links.

We should audit and fix these links in the Gatsby portion of the site.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3521

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/site-baseurl-clear/)

Changes proposed in this pull request:

- Removes deprecated `site.baseurl` variable from state markdown link paths

### CODE REVIEW

**Comment by jennmalcolm** [comment]
The links to the case studies are not working in the preview. Will they be in production?

**Comment by master12** [comment]
@jennmalcolm They should work in preview. Taking a look at it now

**Comment by jennmalcolm** [comment]
The links still don't work for me. I also noticed that Arizona isn't in the state drop down on this branch.

image

**Comment by master12** [comment]
@jennmalcolm The build just finished an hour ago so you might have been quick on the draw. I will look at the arizona issue

**Pull request merged**
