### PR TITLE
Option to add CY and FY to state page intro lines

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[🐢 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/add-fy-and-cy/explore/WY)

Changes proposed in this pull request:

- Adds CY and FY labels to state page intro data points

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
Thoughts about this approach in the interim, @mcharg and @jennmalcolm? It gets a little busy, but does serve the purpose of differentiating the timeframes.

Wyoming revenue data intro 7 energy or mineral commodities were produced on federal land in Wyoming in calendar year 2018.4 commodities were withheld in 2018. Production on federal land in Wyoming resulted in $1,246,326,179 in calendar year 2018 revenue. Revenue from federal land resulted in $641,109,256 disbursed from the federal government to Wyoming in fiscal year 2019.

**Comment by mcharg** [comment]
I think that's better.

**Comment by jennmalcolm** [comment]
I agree it’s worthwhile to add for the sake of clarity even though it’s not ideal that we have the different timeframes mixed on the page. Should I merge or do you want to keep as WIP?

**Comment by brentryanjohnson** [comment]
I say we merge! 👍

**Pull request merged**
