### PR TITLE
dev-->master v5.3.0

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Restyles revenue trends based on user research
- Adds map navigation item for state page templates
- Adds copy for no search result
- Adds blog post about intern contributions
- Adds archive page for USEITI content no longer maintained
- Restructures about content and navigation items
- Refactors some components to use React hooks

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@mojobnichols Please review the error in CircleCI.

**Comment by mcharg** [comment]
I'm getting this error in Firefox.  Will check on my personal computer to see if it's a DOI thing. 
image

**Comment by lpgoldstein** [comment]
I get a 404 for these links: 
https://federalist-proxy.app.cloud.gov/downloads
https://federalist-proxy.app.cloud.gov/downloads/
image

**Comment by mcharg** [comment]
I'm seeing the same thing.

**Comment by brentryanjohnson** [comment]
Yes, it's because of the relative paths @mcharg and @lpgoldstein. The footer is one of the only components that doesn't include the hack to fix links in federalist. Those will be fine in production.

**Pull request merged**
