### PR TITLE
Added tabindex to stacks in stacked bar chart; have event call callba…

### LINKED ISSUE #4477: Add year selectors to homepage charts
## Expected Behavior

- Keyboard users can change selected year on homepage charts

## Actual Behavior

- The only way to select a different year and access the content is by using the mouse to click on a different bar

## Steps to reproduce the behavior

- Attempt to navigate the homepage using just the keyboard

### PR DESCRIPTION
**Pull request by mojobnichols**
…ck so enter triggers a change;  Added tabindex to tabordian tabs and wired them to call callback if keycode is enter

Fixes #4477 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4477-YearSelectors/)

Changes proposed in this pull request:

Tab takes you to bar chart year selectors
Enter selects year changing legend
Caveat it returns you to the first bar after selecting so you have to tab through.

-
-
-

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
This is awesome, @mojobnichols! We might just want to suppress the visual focus on click, since it creates a visual barrier between the selected tab and the content below, disconnected the two.

**Comment by brentryanjohnson** [comment]
@mcharg When you click (or tab) any tab, it now inherits a blue focus border, which visually separates it from the content it introduces.

Tabs of Revenue, Disbursements, Production, and Data by state, with Disbursements tab with blue focus border

**Comment by mcharg** [comment]
@brentryanjohnson Gotcha.  Yeah, makes sense to drop it from the tabs.

**Comment by mcharg** [comment]
@mojobnichols I didn't test this in other browsers and just noticed that it's not working in Edge. It's skips over the chart.

**Comment by jennmalcolm** [comment]
@brentryanjohnson are you ready to approve since you have #4612 for the visual focus? @mojobnichols could you look at the issue in Edge that it skips over the bar chart? I just checked and confirmed the issue.

**Comment by jennmalcolm** [comment]
Added #4629 for remaining issues.

**Pull request merged**
