### PR TITLE
4004 revenue by county maps

### LINKED ISSUE #4004: Revenue by county maps missing on state pages
Revenue by county maps are missing on state pages.

## Production
Revenue from production on federal land by county section with drop down but no content

## Before
Revenue by county section showing choropleth map of relative revenue

### PR DESCRIPTION
**Pull request by master12**
Fixes #4004

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4004-revenue-by-county-maps/explore/TX/#federal-revenue)

Changes proposed in this pull request:

- Add county map table to revenue section
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
This might be the way it was before, but it seems strange to have the heading for the county revenue maps say "County production." @brentryanjohnson, do you think we should say "Revenues by county"?

image

**Comment by brentryanjohnson** [comment]
Agreed, @jennmalcolm. Before it read "Revenue collected by county," but I think "Revenue by county" is a simpler alternative. Also, I wonder if we should change "County revenue in 2018" to "Revenue by county in 2018." It's more wordy, but the former makes it sound like all that revenue might have gone to the county, rather than been generated in that county.

map of Wyoming counties showing revenue concentrations by county ranging from $0 to $570 million

**Comment by brentryanjohnson** [comment]
@master12 Copy changes needed in the county revenue table:

- Remove single quotes on `'Revenue'`
- Add dollar sign in both revenue references in table
- Add the word "County" after the county name
- Using the Campbell County example, reword sentence to read:
  - Companies paid $469,388,928 to extract natural resources on federal land in Campbell County in 2018.

Revenue by county table for Wyoming highlighting changes to add dollar sign, reword, and remove single quotes

**Comment by jennmalcolm** [comment]
This is looking pretty good. I noticed two remaining issues.

1. Add "$" to the standalone number and the numbers in the sentences in the county table.
2. Change the word "county" to "parish" for LA and "borough or census area" for AK.

Thanks

**Comment by jennmalcolm** [comment]
@master12 the data that you merged in here from @brentryanjohnson had some issues. The data in #4121 is the corrected version. Will that override the data in here?

**Comment by jennmalcolm** [comment]
@master12 the county/parish/borough thing may be harder than I thought according to @brentryanjohnson. 

I could create a new issue for that, but could you add the "$" and then we can maybe get this released. I would like to do a release tomorrow. Thanks

**Comment by brentryanjohnson** [comment]
I added the word 'County' to the table copy. 👆 We'll need to write logic to replace with "Parish" or "Borough" for relevant instances in a future sprint. cc @master12 and @jennmalcolm

**Comment by jennmalcolm** [comment]
I almost forgot that the revenue data update with the incorrect labels was merged in here. So I think we will need to wait until #4121 is done to merge this to dev (and deal with merge conflicts). Is that the right approach @master12 and @brentryanjohnson?

**Comment by master12** [comment]
Closing this request due to these changes will be in another PR

**Pull request closed without merging**
