### PR TITLE
Fix glossary bug

### PR DESCRIPTION
**Pull request by master12**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/fix-glossary-bug/)

Changes proposed in this pull request:

- fix bug in displaying glossary after clicking a term
-
-

### CODE REVIEW

**Comment by master12** [comment]
OK check out the glossary!

**Comment by mcharg** [comment]
The glossary is working (except the icons are broken in IE), but the charts are missing in all the sections except Disbursements and the Nationwide menu is broken on mobile.

**Comment by master12** [comment]
ugh, had the wrong setting in sourcetree so it was committing all the files properly. Added them now. Please hold...

**Comment by master12** [comment]
Ok site is up again. 

IE 11 icons missing is  asecurity setting. I think our federalist site is not trusted and hence downloads of fonts might be disabled. It alos might explain other weird behavior in IE. I tested on my persnal machine and the icons work just fine

**Pull request merged**
