### PR TITLE
Fix name on legend

### LINKED ISSUE #3392: Fix remaining homepage bugs
Fix the issues that weren't show stoppers for the release.

On hover, the swatches in the table should change to the hover color.

- [x] Fixed

- [x] Tested

Table header for the month should have the year after the month name. (e.g. Mar 2018)

- [x] Fixed

- [x] Tested

Production charts aren't moving together on click.
- [x] Fixed

- [x] Tested

Could use a bit more space between the primary nav and tabs.
- [x] Fixed

- [x] Tested

Period drop-down is misaligned and missing the arrow on IE.  It does at least work, so users can get to the content, so I'm not putting this in show stoppers.
image
image

- [x] Fixed

- [x] Tested

### PR DESCRIPTION
**Pull request by master12**
Fixes #3392

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/fix-name-on-legend//)

Changes proposed in this pull request:

- Added an option to set the display names in the reducers
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
I'm not sure if this happened here or with another PR, but we seem to have lost "calendar year" under the x axis of the revenue graph. Can we put that back on?

Preview:
image

Production:
image

**Comment by mcharg** [comment]
"Calendar year" looks fixed, but it's back to saying "Fiscal year 2017" in the drop-down.

**Comment by master12** [comment]
The fix for that is not in the PR. I just merge the patch to dev so you will see it there.

**Comment by master12** [comment]
ok just merged dev into this branch to fix the conflict so the fix should be seen in 15 mins

**Pull request merged**
