### PR TITLE
Fixes accessibility issues from Pa11y on homepage

### LINKED ISSUE #4068: Fix accessibility issues from Pa11y audit: duplicate ids
• Error: Duplicate id attribute value "backgroundRect" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #backgroundRect
└──

• Error: Duplicate id attribute value "maxExtent" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #maxExtent
└── <text width="300" x="300" y="15...

• Error: Duplicate id attribute value "bars" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #bars
└── <g height="175" width="21.21212...

• Error: Duplicate id attribute value "groups" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #groups
└── <line x1="4.242424242424243" x2...

• Error: Duplicate id attribute value "backgroundRect" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #backgroundRect
└──

• Error: Duplicate id attribute value "maxExtent" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #maxExtent
└── <text width="300" x="300" y="15...

• Error: Duplicate id attribute value "bars" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #bars
└── <g height="175" width="21.21212...

• Error: Duplicate id attribute value "groups" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #groups
└── <line x1="4.242424242424243" x2...

• Error: Duplicate id attribute value "backgroundRect" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #backgroundRect
└──

• Error: Duplicate id attribute value "maxExtent" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #maxExtent
└── <text width="300" x="300" y="15...

• Error: Duplicate id attribute value "bars" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #bars
└── <g height="175" width="21.21212...

• Error: Duplicate id attribute value "groups" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #groups
└── <line x1="4.242424242424243" x2...

• Error: Duplicate id attribute value "backgroundRect" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #backgroundRect
└──

• Error: Duplicate id attribute value "maxExtent" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #maxExtent
└── <text width="349" x="349" y="15...

• Error: Duplicate id attribute value "bars" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #bars
└── <g height="175" width="24.67676...

• Error: Duplicate id attribute value "groups" found on the web page.
├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
├── #groups
└── <line x1="4.935353535353537" x2...

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #4068

[:sunglasses: REVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4068-FixAccessibilityIssues/)

Updates made to this branch include:
- Remove the id attribute from the section element on home page/index page
- The id gets applied to the H2 element

Pa11y command for testing:

`pa11y --wait 1000 --debug https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4068-FixAccessibilityIssues/`

Current response being seen in branch:

`Welcome to Pa11y`  
`Running Pa11y on URL https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4068-FixAccessibilityIssues/`    
`Debug: Launching Headless Chrome`
`Debug: Opening URL in Headless Chrome`
`Debug: Browser Console: JSHandle@object mark`
`Debug: Loading runner: htmlcs`
`Debug: Injecting Pa11y`
`Debug: Injecting runner: htmlcs`
`Debug: Running Pa11y on the page`
`Debug: Waiting for 1000ms`
`Debug: Document title: "Home | Natural Resources Revenue Data"`

`No issues found!`

### CODE REVIEW

**Comment by jlouis-onrr** [comment]
@brentryanjohnson Yes I agree the border shouldn't have gone rogue.  That was an oversight on my part.  I will look into adding the border back in without utilizing an empty header tag.

**Comment by brentryanjohnson** [comment]
It's still building, so I haven't seen the preview, but `span` seems like a good solution to me. It uses an existing class, it's semantically inert, and should result in the same visual style. Sounds good!

I'll check out the preview tomorrow.

**Comment by brentryanjohnson** [comment]
@jlouis-onrr It looks like there is extra space introduced with the non-breaking space (compare with production).

While the extra space isn't offensive, I don't know that the `&nbsp;` is the best way to add that space. It can probably be omitted, if the empty `span` doesn't trigger audit failures.

**Comment by jlouis-onrr** [comment]
@brentryanjohnson  Missed the extra spacing that was created from that.  I'll adjust it.  Is there a design comp that I can reference for spacing, margins, etc?

**Comment by mcharg** [comment]
@jlouis-onrr We don't do comps, but the prototype for the homepage is here and may get you what you need in terms of spacing. https://sjzq35.axshare.com/#g=1&p=alt_tab_styling

**Comment by jlouis-onrr** [comment]
Perfect, thanks! @mcharg

**Comment by jlouis-onrr** [comment]
@brentryanjohnson - Removed non-breaking space from span tag, doesn't appear to throw any accessibility issues.  Just pushed up and should be visible in awhile. 

[Branch - 4068-FixAccessibilityIssues](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4068-FixAccessibilityIssues/)

**Comment by jlouis-onrr** [comment]
@mcharg Don't know if this should go here, but just noticed this broken styleguide link on the wiki page.

https://github.com/ONRR/doi-extractives-data/wiki/Joining-the-Natural-Resources-Revenue-Data-project-team

Styleguide is currently pointing at: (https://revenuedata.doi.gov/patterns/)

Is this related to the pattern library issue? #3329

**Comment by mcharg** [comment]
@jlouis-onrr Yeah, it is related to that issue.  The new pattern library was live for a while, but it got taken down.

**Comment by mcharg** [comment]
We have a copy of the old pattern library in a federalist branch, for reference. https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/aml-spark/styleguide/

**Comment by jlouis-onrr** [comment]
@mcharg Right on, thats good to know.  thank you.

**Pull request merged**
