### PR TITLE
Adds 2018 company revenue data

### LINKED ISSUE #4072: Update Revenue by Company
- [x] Check data to ensure it conforms to previous file format

- [x] Check data accuracy 

- [x] Update the revenue by company download file

- [x] update contextual language to reflect the additional year

- [x] Update the revenue by company visual 

Data File 
[federal_revenue_by_company_CY2013-CY2018 (3).xlsx](https://github.com/ONRR/doi-extractives-data/files/3173638/federal_revenue_by_company_CY2013-CY2018.3.xlsx)

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #4072

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/2018-company-revenue/how-it-works/federal-revenue-by-company/2018/)

Changes proposed in this pull request:

- Adds 2018 company revenue

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
I ran the `makefile` and generated the 2018 output company revenue file, but it appears we may have lost the logic to generate the page and resulting tabular data. We may need to build the logic to generate it, @master12.

**Comment by brentryanjohnson** [comment]
For documentation purposes, here some additional steps to publish the data (apart from the `makefile` transformations), since we haven't been able to complete our Gatsby transition workflow due to other demands on time:

- Requires the addition of a dedicated markdown file for each year, created in `src-->markdown-->how-it-works`. (see, for example, `2018.md` for format)
- Also requires adding the navigation item for the new year's data, found in `src-->templates-->how-it-works-revenue-by-company.js` like so:
``` 
<li className={(reportYear === 2018) ? 'explore-subpage-tab active' : 'explore-subpage-tab'}>
     <Link to="/how-it-works/federal-revenue-by-company/2018/">2018</Link>
</li>
```

**Comment by mentastc** [comment]
I think we should add somewhere that this is a CY data set, we're starting to use FY more in visuals on the site so I no longer think the user can assume it's CY

**Comment by brentryanjohnson** [comment]
Okay @mentastc, it's added to the template.

**Comment by brentryanjohnson** [comment]
I was going to add the data file in a separate branch, but I'll do that in this branch, too.

**Comment by brentryanjohnson** [comment]
Notes on the origin data file versus historic files:

- The data files driving company revenue don't contain a year field, since each year is its own file.
- The new file column is "Corporate Name," versus "Company" in previous files.
- The new file column is "Revenues" versus "Revenue" in previous files.

**Comment by brentryanjohnson** [comment]
@mentastc Please also review the [downloads](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/2018-company-revenue/downloads/federal-revenue-by-company/) update now that the build is complete.

**Comment by jennmalcolm** [comment]
@mentastc do you want to take a look at the downloads before we merge this PR?

**Comment by mentastc** [comment]
Looks good! Merge when ready

**Pull request merged**
