### PR TITLE
Changes repo path in preview plugin, site footer, and other instances

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/repo-transfer/)

Changes proposed in this pull request:

- Changes Ruby plugin for preview path to ONRR org
- Updates github paths to new org location

### CODE REVIEW

**Comment by mcharg** [comment]
The preview link doesn't work.

**Comment by brentryanjohnson** [comment]
Indeed, @mcharg. I'll look into this.

**Comment by brentryanjohnson** [comment]
@mcharg The preview link should work now (must lowercase the org name in the file path), but I need to change the casing in the individual files in this PR now.

**Comment by mcharg** [comment]
@brentryanjohnson It is working (in my phone). I’m at the airport, so won’t be able to review the PR until I get home.

**Comment by brentryanjohnson** [comment]
@mcharg FYI...many of these changes won't show up in the preview, because they are changes to config files, etc., and don't present visually on the website.

**Pull request merged**
