### PR TITLE
Adds smooth scrolling to gatsby pages

### LINKED ISSUE #3161: Add smooth scrolling to Gatsby explore data
We decided to test smooth scrolling to assist users with wayfinding on the explore data page, but the Gatsby version of `explore` doesn't appear to reference the same style sheet, which means it will have aberrant scroll behavior compared to the other pages of the site.

We should add the smooth scroll behavior to the Gatsby version of the explore data page.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3161 

[:turkey: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/gatz-smooth-scroll/explore/)

Changes proposed in this pull request:

- Adds smooth scrolling property to GatsbyJS portion of the site

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
I'd like to know what you think about this behavior, @mcharg. It's a little jolting on a page this long, but it also orients the user to their relative location on the page. It's a trade-off we'll want to continue to evaluate.

**Comment by mcharg** [comment]
@brentryanjohnson Can we try slowing down the scrolling or making the speed relative to how much content you're scrolling through?

**Comment by mcharg** [comment]
I'm fine with going with this and seeing if we get complaints from users.

**Comment by brentryanjohnson** [comment]
I'm sensitive to the user responses, and it would be good to get as much feedback as possible. As I mentioned before, there is the possibility of triggering vestibular issues for some people. We're weighing the drawbacks against what we assume will be a better orienteering awareness on that long page of content. Let's assess repeatedly.

**Pull request merged**
