### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

Changes made in this release:

- Publish third blog post on usability testing training
- Update fiscal year revenue data file
- Update monthly revenue and production data
- Fix anchor link problem
- Convert revenue streams and rate image to markdown table
- Convert archive key to boolean
- Fix other minor bugs

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
Looks like it built just fine, @jennmalcolm

**Comment by mentastc** [comment]
In the revenues when you're looking at yearly why doesn't 2019 show up??

**Comment by mcharg** [comment]
@mentastc We're only showing full years, so 2019 won't be in the yearly view until next January.

**Comment by jennmalcolm** [comment]
That does beg the question why we don't handle the yearly graphs for production and revenues in the same way.

**Pull request merged**
