### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Adds first iteration of filterable revenue table
- Updates monthly graphs and download files
- Hides search until it can be implemented again
- Migrates executive summaries to new site structure
- Updates packages for blog site
- removes tax section under explore revenue
- Other minor edits

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Things to check

Navigate between pages
- [ ] Check several types of location profile page to ensure data and liquid templates are working as expected
- [ ] Check links are working correctly
- [ ] Check drop downs menu and validate they work 

Text
- [ ] No misspelling
- [ ] Correct spacing
- [ ] Correct format
- [ ] Accurate dates displayed

Data [Detailed instructions (limited access) ](https://docs.google.com/document/d/1ypXgw9yEETx9T-ZlDOTULeysaws3qKsfRLV6mOygB3I/edit)
- [ ] Review 1 verified 5-10 sample lines of data--against source data and relevant charts (Assigned commodities)
- [ ] Review 2 verified 5-10 sample lines of data--against source data and relevant charts (Assigned commodities)

Bar Charts
- [ ] Hover behavior is working 
- [ ] Data displayed is correct
- [ ] Chart changes if you select yearly or monthly

Check all browsers
- [ ] Chrome
- [ ] Internet Explorer
- [ ] Safari
- [ ] Firefox
- [ ] Edge

Check all devices
- [ ] Dell Laptop
- [ ] Chromebook
- [ ] Macbook
- [ ] iPad
- [ ] iPhones
- [ ] Samsung phones

Check all responsive breakpoints
- [ ] < 480 px (switches to one-column layout)
- [ ] 600 px (changes bar chart layout from three column to accordion with one column)
- [ ] 768 px (converts side navigation from separate column to the right to a select list)
- [ ] > 768 (full site layout)

**Comment by mcharg** [comment]
I'm getting a 404 error when clicking on executive summaries from About page.
image

https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/about/report

**Comment by brentryanjohnson** [comment]
Good catch, @mcharg. I opened a separate PR with the fix that we can merge into `dev` before release.

**Comment by mcharg** [comment]
I noticed a bunch of issues in IE, Edge, and Firefox on the filterable table that I created new issues for.

**Pull request merged**
