### PR TITLE
Added alt styling to tabordian

### LINKED ISSUE #4387: Build tab component for homepage
https://sjzq35.axshare.com/#g=1&p=alt_tab_styling

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #4387

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4387-Tabordian/)

Changes proposed in this pull request:

This brings in alt tab styling into  the Tabordian component. 
-

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols Overall, the styling looks good.

The disbursements tab is missing the vertical rule on the right.
image

**Comment by mcharg** [comment]
@mojobnichols Disbursements is still missing the right rule and there's a horizontal rule under the selected tab that shouldn't be there.  (in Chrome)
image

**Comment by brentryanjohnson** [comment]
In addition to the borders, which I can help with @mojobnichols, the accordion behavior isn't working on mobile. It appears to do so in the mobile view in the inspector, but on the phone it doesn't work.

Screenshot of mobile view of homepage showing tab for overview, but missing other tabs for revenue, disbursements, and production

**Comment by mcharg** [comment]
@brentryanjohnson The other accordions are there on my phone.

**Comment by brentryanjohnson** [comment]
I see them now after a couple refreshes. The bottom border disconnects the content from the tab, though. We should restyle the media query.

**Comment by brentryanjohnson** [comment]
FYI @mojobnichols and @mcharg 

☝️ Fixes issues with border styling. Also changes `box-shadow` property to `border-top` property to avoid duplicate appearance of "top borders".

## Previous
tab interface with missing right border on disbursements tab and persistent border below active tab

## After these commits
tab interface with right border on last tab for disbursements and no border under active tab

**Comment by brentryanjohnson** [comment]
☝️ Attempts to better connect tabs to content.

## Previous
mobile view of overview tab with bottom border disconnecting content from tab

## After commit
styles overview tab to remove bottom border to better connect with content that follows

**Comment by brentryanjohnson** [comment]
☝️ Removes padding on revenue trends and gives breathing room on small viewports.

## Previous
Revenue trends line charts and data push out to right from screen, not centered in viewport

## After commit
Revenue trends line chart and data section centered in screen with generous margin at top

**Comment by mcharg** [comment]
For mobile, since the whole page will now be changing with the tab selection, it might make sense to have the tabs all be at the top.  The accordions made sense when it was just one section that was changing.  Having the tabs all at the top will make it easier for users to jump to the section they want without having to scroll through Revenue first.  Thoughts? @brentryanjohnson 

If we did that, all of the tabs would looks like the disbursements one looks now.
image

**Comment by mcharg** [comment]
Note: This PR shouldn't be merged into dev until we finish building the new homepage.  This styling doesn't work with the current homepage content.

**Comment by mcharg** [comment]
@brentryanjohnson @mojobnichols This is what I was trying to describe for how the tabs could work on mobile.

https://sjzq35.axshare.com/#g=1&p=alt_tab_styling&view=a

**Comment by jennmalcolm** [comment]
Closing since this is in #4174 now

**Pull request closed without merging**
