### PR TITLE
Heavy, chunky font

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/heavy-ugly-font/)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@brentryanjohnson You're right, bold does become hard to differentiate.
image

**Comment by mcharg** [comment]
@brentryanjohnson I'm not finding bold text in any other location on the site.  Maybe we just address the few spots where we use it by using other means to give the content more weight?

**Comment by brentryanjohnson** [comment]
I'm still working on this branch, @mcharg, but there will be more instances where the problems emerge. I'll let you know when I've increased the weight of all instances of "light" to "regular".

**Comment by jennmalcolm** [comment]
How difficult will it be for you to put together a branch to preview changing from almost black to black to see if maybe that will address the concerns without having to go to such heaving text?

**Comment by brentryanjohnson** [comment]
Color tweak (only) is in #4079, @jennmalcolm.

**Comment by brentryanjohnson** [comment]
I've changed the default body font weight from `500` in the previous iteration to `400` to determine if that helps preserve emphasis contrast.

**Comment by mcharg** [comment]
Looks a little better.

**Pull request merged**
