### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:
- Adds accessibility blog
- Updates monthly production through June 2019
- Updates monthly and annual disbursements through Sep 2019/FY19
- Updates monthly and annual revenues through Sep 2019/FY19
- Addresses accessibility errors
- Adds Federal - not tied to lease to homepage revenue chart
- Fixed totals inconsistencies due to rounding
- Updated LWCF content
- Other minor updates

Places to check data:
Production Monthly (monthly_production)	
- [x] Homepage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Hompage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Fiscal Year (fiscal_year_revenue)	
- [x] Homepage: FY bar charts
- [x] Homepage revenu choropleth map
- [x] How it works: Native American revenue table 
- [x] Explore data: Filterable revenue data table 
- [x] Download: xls and csv files updated with correct dates and file size

Disbursements Monthly (monthly_disbursements) 	
- [x] Homepage: disbursements trends
- [ ] Download: xls and csv files updated with correct dates and file size

Disbursements Fiscal Year (disbursements)	
- [x] Homepage: FY bar chart
- [x] Explore data: by recipient table
- [ ] Download: xls and csv files updated with correct dates and file size"
- [x] State page disbursements

### CODE REVIEW

**Comment by lpgoldstein** [comment]
We need to update the scope on fy disbursements dowlnoad page to include 2019 
image

**Comment by lpgoldstein** [comment]
also unsure about file size for fy disbursements because they keep showing up as different sizes when I download - slightly different than the ones listed in dev

**Comment by mentastc** [comment]
Disbursement numbers are right but on the state pages with offshore it no longer breaks out offshore from onshore. 
Dev
image

Live site
image

**Comment by jennmalcolm** [comment]
As long as the data is correct, we can make new issues for little stuff like the scope update and the offshore onshore breakdown on the state pages so we can get this merged. We can address the little stuff in a patch release next week.

**Comment by mentastc** [comment]
Disbursement by year xls file size is wrong should be 84 not 64

**Comment by jennmalcolm** [comment]
Ok, @mentastc or @lpgoldstein could you create an issue with the cleanup items you've found?

**Comment by mentastc** [comment]
csv sizes don't match and change when I open them.

**Comment by lpgoldstein** [comment]
@mentastc I'm getting the same issue with the disbursements file size

**Pull request merged**
