### PR TITLE
4205 query tool

### LINKED ISSUE #4205: Fix usability issues with revenue filterable table/build query tool
New design is in #4411.

### PR DESCRIPTION
**Pull request by master12**
Fixes #4205 

[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/onrr/doi-extractives-data/4205-query-tool/query-data/)

Changes proposed in this pull request:

- New filterable SMARTER table

## Revenue changes
- [x] If "All land categories" is selected, the Native American withheld note needs to be displayed.
- [x] If "Onshore" is selected, the Native American withheld note needs to be displayed.
- [ ] If "All" or "Onshore" are selected, "All" should be the only option in the location drop-down.
- [x] Add "Select a federal-only land category to view location." to the end of the Native American withheld note.
- [x] How It Works link should be "How revenue works" and use the How it works icon from the homepage.
- [ ] The "All" checkbox for all drop-downs with one should select/unselect all the other checkboxes when it's checked or unchecked.

## Production changes
- [x] Units are missing for everything except geothermal.
- [x] Commodity should be the only column displayed by default (users can opt to add a second column) until a single commodity is selected.  Otherwise, it's comparing apples and oranges with the different units.
- [ ] When the commodity column is the only one showing by default, the user should still have the option to edit the groupings and add an additional column.
- [ ] Rows with only withheld data should be hidden by default with a checkbox to add them in. 
image
- [x] If "All land categories" is selected, the Native American withheld note needs to be displayed.
- [x] If "Onshore" is selected, the Native American withheld note needs to be displayed.
- [ ] If "All" or "Onshore" are selected, "All" should be the only option in the location drop-down.
- [x] Add "Select a federal-only land category to view location." to the end of the Native American withheld note.
- [x] How It Works link should be "How production works" and use the How it works icon from the homepage.
- [ ] The "All" checkbox for all drop-downs with one should select/unselect all the other checkboxes when it's checked or unchecked.

## Disbursements changes
- [x] How It Works link should be "How disbursements work" and use the How it works icon from the homepage.
- [ ] The "All" checkbox for all drop-downs with one should select/unselect all the other checkboxes when it's checked or unchecked.
- [ ] Remove the "onshore & offshore" option from the source drop-down. These lines should still display if the user selects "All" sources.

## No data changes (applies to all data sets)
- [ ] Only display rows when there is data for at least one year the user has selected.
- [ ] If there are years with no data in the user's selection, but numbers for at least one other visible year, the years with no data get a dash.

## Access to the table
- [ ] Set up the page, so we can link to revenue, production, or disbursements.
- [x] Add "Filter production data" and "Production in detail" links to the Production homepage tab following the same pattern as the Revenue links.
- [x] Add "Filter disbursements data" and "Disbursements in detail" links to the Disbursements homepage tab following the same pattern as the Revenue links.
- [x] Add "Production data in detail" link to the left of the documentation link on the Explore data page.
- [ ] Add "Disbursements data in detail" link to the left of the documentation link on the Explore data page.
- [ ] Update the icon on the "Revenue data in detail" links to the table icon (see #4646).

## Fit and finish 
- [x] Make it so we don't cut off content when there are a large number of columns.  It's unusable if you can't read the numbers or labels.
image

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 See above for initial list of changes.

**Comment by jennmalcolm** [comment]
@Maroyafaied @mentastc and @lpgoldstein, while Jeff is working on the logic, I think we should start reviewing the data in the query tool. Please go through a variety of different queries on the revenue data to make sure it is all ok. You can work together to divide it up so there's no overlap.

**Comment by mcharg** [comment]
@master12 I added items above for production.

**Comment by jennmalcolm** [comment]
Work continued in #4616

**Comment by mcharg** [comment]
@master12 In the latest preview, you can't get to the production data. There's no next drop-down after picking production.
image

**Comment by mcharg** [comment]
And disbursements completely breaks when you pick the "All" source.  The page goes blank.
image

**Comment by mcharg** [comment]
For production, the revenue type and fiscal year start drop-downs are showing up at the same time after picking commodity.
image

**Comment by mcharg** [comment]
Disbursements - fiscal year drop-down is blank if you select an individual source.
image

**Comment by mcharg** [comment]
@master12 Revenue is really close.  I updated the checklist for revenue above to reflect just the things that are still issues.

**Comment by mcharg** [comment]
@master12 The checklist for production is updated above.

**Comment by mcharg** [comment]
@master12 The disbursements list is updated.

**Comment by master12** [comment]
@mcharg I have a question about this issue "The years should be ordered from oldest to newest." We have a lot of years now and you have to actually scroll down to see the last few when you have all the years. My thought is that ppl really want the latest numbers so I made it easy for them by having the newest years at the top.

**Comment by master12** [comment]
@mcharg I think I got everything for all data types. The include withheld for Prod we need to talk. The fit and finish, the columns are now resizeable and also the first column is now fixed when you scroll.

Happy Testing!

**Comment by mcharg** [comment]
@master12 If feels backwards to me when using the date selector.  What do others think? @brentryanjohnson @jennmalcolm @lpgoldstein

**Comment by mcharg** [comment]
@master12 When you pick with "All" or "Onshore" as land category, you shouldn't be able to pick a location. You can default to "All" and have that be the only option in the drop-down.

**Comment by mcharg** [comment]
@master12 If you go from all commodities in production to a single commodity, the submit button disappears.
image

**Comment by jennmalcolm** [comment]
I think having the most recent at the top works since people will probably want to look at the more recent years more often than the older stuff. 

@mcharg what is the difference between "all" and "onshore and offshore" in the source under disbursements?

**Comment by mcharg** [comment]
@master12 On the production change to only show the commodity column by default, the user should still have the option to edit the groupings and add an additional column.

**Comment by mcharg** [comment]
@jennmalcolm The onshore & offshore is the line in the spreadsheet that is the items that can't be split between onshore and offshore.  I'm wondering if we should drop that as an option and just include those lines if the user picks all.

**Comment by jennmalcolm** [comment]
Oh @mcharg I figured out what it is. The "onshore and offshore" category is only for the pre-2008 data that we don't have broken down by onshore or offshore. Do you think it's going to cuase confusion to have that as a choice in the source dropdown?

**Comment by mcharg** [comment]
@master12 I'm putting changes in new comments because GitHub won't let me edit the original comment any more.

**Comment by mcharg** [comment]
@jennmalcolm Yes, I do think it will cause confusion because both you and I were confused by it when we first say it.

**Comment by mcharg** [comment]
@master12 went through the checklist and checked off the things that are satisfactorily fixed and put new comments in where things need tweaking.

**Comment by mcharg** [comment]
@master12 It's letting me edit again, so the checklist is now updated.

**Comment by jennmalcolm** [comment]
@mentastc and @lpgoldstein please review all of the data in here.

**Comment by master12** [comment]
Fixes #4679 completed

**Comment by mcharg** [comment]
@master12 The commodity column is still the only column when you don't select a single column. I thought you were going to remove that logic, so we can get the ability to change columns back.
image

**Comment by mcharg** [comment]
@master12 I think you did the onshore & offshore source change backwards.  It's now the only option in the source drop-down.
image

**Comment by mcharg** [comment]
@master12 The second revenue in detail link on Explore Data didn't get the new icon.
image

**Comment by master12** [comment]
Please review @mcharg

**Comment by jennmalcolm** [comment]
@mentastc @lpgoldstein @Maroyafaied please work together and divide up the work to check the numbers. We want to get this released next week.

**Comment by mentastc** [comment]
@lpgoldstein and @Maroyafaied  I'll start looking at the revenue data and move to production once I finish.

**Comment by Maroyafaied** [comment]
@jennmalcolm @mentastc @lpgoldstein  I will start checking disbursement data.

**Comment by Maroyafaied** [comment]
@master12 @jennmalcolm  The data for disbursements is correct and looks good. The only thing I found confusing is when you select just one county for a state , the table doesn't name that specific county, it instead says "State". But if you select more the one county, it does list the county names in the table. 
image
 
image

**Comment by Maroyafaied** [comment]
@master12 the county names don't show up alphabetically. 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied it looks like it's sorting it by the volume from the most recent year. That down arrow in the top right corner of your screen shot indicates that.

**Comment by Maroyafaied** [comment]
@master12 when you select production, then onshore, on the location dropdown there is two withheld options. 
image

**Comment by master12** [comment]
@Maroyafaied The county thing is by design. You can see the column name is different. The idea is since you only have 1 county you know which county you are looking at so you see the Recipient of the funds which was the State. 

I will fix the withheld text. Thanks

**Comment by jennmalcolm** [comment]
@master12, when there is a county listed in the disbursement file, the disbursement recipient is the county, not the state. So, I agree with @Maroyafaied that the one county should be listed as the recipient, rather than the sate. We also should probably make the dropdown for recipient say "states and counties," but that's something that's no urgent, so I'll add it to #4764.

**Comment by master12** [comment]
@jennmalcolm The recipient is the the fund type. Are you suggesting changing the fund type to County vs State? If thats what you want I would suggest changing the data.

**Comment by mcharg** [comment]
@master12 We should update all the recipient labels in the drop-down to match what's in the disbursements summary on Explore Data.  The Native American one, in particular, was vetted with a lot of folks when we did that design.

**Comment by master12** [comment]
Ok calling shenanigans on our data labeling again. Supposedly there will be a metadata initiative with Data Gov. We need to make that a must have priority that gets done ASAP. I'll try to think of something that will allow you to change the names of stuff since it seems to be an ongoing change. However this should really be resolved in our data and not in our code.

**Comment by jennmalcolm** [comment]
@master12 my  suggestion was to just change the label on the dropdown because you have to go through a state to get county disbursements, but we probably should have the fund type in the data file changed to county when the disbursements are going directly to the county. That would then allow people to use the query tool to see counties in more than one state I would imagine. We can work on that later. I don't think it's something to hold up the release.

**Comment by mentastc** [comment]
@lpgoldstein @Maroyafaied, @jennmalcolm  asked that each of the data sets is checked by multiple people so we should all check at least two of the data sets or all three if we have time.

**Comment by Maroyafaied** [comment]
@master12 @jennmalcolm Ok I checked production and disbursement , I'll go ahead and check revenue as well. Thanks

**Comment by master12** [comment]
tough to talk about this in github, but we can sync up when i have communications again

**Comment by Maroyafaied** [comment]
@master12 @jennmalcolm I just finished checking revenue data, the data looks good. The only thing I found confusing is that the revenue type dropdown selection does not have the check boxes like the other selections, so you can only chose one revenue type or the "All" option.  It would be nice if for example , the user can select Rents and Royalties, rather than just one of them. 
image

**Comment by lpgoldstein** [comment]
The "production/revenue/disbursement detail" links are on the explore data page but they don't include the word "data"

**Comment by lpgoldstein** [comment]
The data looks good.

**Comment by jennmalcolm** [comment]
@lpgoldstein @Maroyafaied and @mentastc for bugs/enhancements that shouldn't hold up release, please add to #4764

**Pull request merged**
