### PR TITLE
updates download files and download page

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #<5092>

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/cyproductionNA/)

Changes proposed in this pull request:

- updates download files
- updates file size and download pages and adds Borrow sand and gravel to product list
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@lpgoldstein you are getting errors on this because the graphQL is not set up for the reformatted production files. That's why we decided to not update the explore data production (since it would require refactoring) and just update the download file. In order to do this, I used a unique file name. The general downloads/production/calendar_year_production.xlsx file is what the explore data is built off, so you should leave it as it is (may require starting over with a new branch). You should replace the files with dates with your new files with the Native American added in. Let me know if that wasn't clear and you want to co-work on this.

**Comment by lpgoldstein** [comment]
@jennmalcolm Got it. I was wondering why the name was different on the previous file and thought it was a mistake I had made.

**Comment by Maroyafaied** [comment]
@lpgoldstein @jennmalcolm is the Native American data supposed to be in CY production file? It's currently not on there.

**Comment by lpgoldstein** [comment]
@Maroyafaied I think I need to change the file the download page is referencing but I need to do school pick up now and will have to fix when I get back. I can have someone else review if you are out for the day.

**Comment by Maroyafaied** [comment]
@lpgoldstein I'll be still working the next couple of hours.

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied Can I close this PR?

**Comment by Maroyafaied** [comment]
> @lpgoldstein @Maroyafaied Can I close this PR?

@mcharg I closed it, thanks for pointing it out.

**Pull request closed without merging**
