### PR TITLE
Converts table image to semantic table for accessibility

### LINKED ISSUE #3067: Replace static image of table with HTML table
The [How it works-->Revenues table](https://revenuedata.doi.gov/how-it-works/revenues/#federal-lands-and-waters) has valuable information, but it's a `png` image with insufficient `alt` text. Consequently, it's content is neither accessible nor machine-readable. Let's replace it with an HTML table.

static table image

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3067

[:cow: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/image-to-table/how-it-works/revenues/#revenue-streams-and-rates)

Changes proposed in this pull request:

- Converts image of table to semantic, structured tabular content
- Omits tax section from table (since it's outdated and doesn't relate to ONRR revenue)

### CODE REVIEW

**Comment by mcharg** [comment]
@brentryanjohnson Can you make the underlines under the Phase header green to match the style in the old style guide? The last example has a spanning header.
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/aml-spark/styleguide/components/detail/basic-table.html

The icons also feel weird in black.  I think they're always green, blue or gray elsewhere.  Would it make sense to match the style for both the header and icon used in the revenue table?
image

**Comment by brentryanjohnson** [comment]
@mcharg The green from the style guide is tied to the `<th>` element, which is why it shows up under the table header in the preview. I can play with the color of the phase border, too, but I'll have to write some custom markup to do so.

The icon is an include, so it's the same markup used most everywhere else for the same icon. When I was working on icons last year, I wrote some CSS whereby the icon inherits the color from its surrounding text (`fill: currentColor`). To make it green, I'll need to duplicate the icon includes and write some custom markup.

Because of the "phase" part of this table, we don't have a pattern that we can apply to the whole table element. I'm using as many existing styles as I can and trying to limit custom markup for this one table.

**Comment by mcharg** [comment]
@brentryanjohnson Probably not worth a lot of custom work to make the icon color change, but I think changing the color on the Phase line is worth a little bit of custom work.

**Comment by jennmalcolm** [comment]
Could we make the column widths for the different phases more consistent between the commodities?

**Comment by mcharg** [comment]
@brentryanjohnson Looks so much better with the green line and that also makes the black icons look better.  I think the black lines were throwing all the visuals off.

I agree with @jennmalcolm about the column widths.

**Comment by mcharg** [comment]
@brentryanjohnson Gotcha.  I think it's okay to leave as is until we get to Gatsby.

**Comment by jennmalcolm** [comment]
Ok, makes sense to me @brentryanjohnson.

**Pull request merged**
