### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)
Changes proposed in this pull request:

- Redesigned homepage tab layout based on user input
- Added disbursements trends summary on homepage
- Changed U.S. map from land ownership to data-driven choropleth (revenue by state)
- Updated revenue rates and links
- Fixed explore data disbursements bug
- Added "skip to main content" keyboard link for accessibility
- Updated disbursements download files

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 On the disbursements summary, GOMESA is still missing for U.S. Treasury and LWCF.

**Comment by brentryanjohnson** [comment]
@master12 It looks like you're rolling the U.S. Treasury GOMESA number into State and local governments GOMESA.

Adding the state GOMESA number to the U.S. Treasury GOMESA number gives us the GOMESA number currently showing up under States and local governments.

screenshot of Excel data with $187 million for state gomesa, and $309 million for US Treasury gomesa

```
  if (fund.includes('GoMESA')) {
    fund = 'State'
    source = 'GOMESA'
  }
  else if (fund.includes('8(g)')) {
    fund = 'State'
    source = '8(g)'
  }
```

**Comment by jennmalcolm** [comment]
Aside from what @brentryanjohnson mentioned, the LWCF GOMESA disbursements are missing, and the total is off by that amount.

**Comment by jennmalcolm** [comment]
@master12 last commit fixed the Treasury/state GOMESA issue, but the LWCF GOMESA number is missing. 

image

**Comment by mcharg** [comment]
@master12 The capitalization is different on the 2018 LWCF GOMESA line, that's why that's the only year not being picked up.
image

**Comment by mcharg** [comment]
@jennmalcolm I took a quick pass through the rest of the changes and I didn't notice anything else that needs to be fixed.

**Comment by master12** [comment]
@jennmalcolm @mcharg Fixed the 2018 LWCF gomesa, give it 20 mins

**Comment by mcharg** [comment]
The drop-downs are all squished together on the filterable table.
image

**Comment by jennmalcolm** [comment]
Thanks @mcharg we can create another issue for the squised dropdowns, but depending when the next iteration is ready, it might be unnecessary.

**Comment by mcharg** [comment]
Yeah, that's why I didn't just create one for it, but thought I should at least point it out.

**Pull request merged**
