### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Correct LWCF amounts for 2015-2016 in disbursements visual
- Clean up punctuation 
- Clean up glossary term syntax
- Transition more How it Works pages (minerals, renewables, AML, revenues, revenue by company, disbursements, coal tax, reconciliation, downloads) to Gatsby

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Navigate between pages
- [ ] Check several types of location profile page to ensure data and liquid templates are working as expected
- [ ] Check links are working correctly
- [ ] Check drop downs menu and validate they work 

Data [Detailed instructions (limited access) ](https://docs.google.com/document/d/1ypXgw9yEETx9T-ZlDOTULeysaws3qKsfRLV6mOygB3I/edit)
- [ ] Review 1 verified 5-10 sample lines of data--against source data and relevant charts (All commodities - Disbursements data - homepage and explore data)
- [ ] Review 2 verified 5-10 sample lines of data--against source data and relevant charts (All commodities - Disbursements data - homepage and explore data))

Check all browsers
- [ ] Chrome
- [ ] Internet Explorer
- [ ] Safari
- [ ] Firefox
- [ ] Edge

Check all devices
- [ ] Dell Laptop
- [ ] Chromebook
- [ ] Macbook
- [ ] iPad
- [ ] iPhones
- [ ] Samsung phones

Check all responsive breakpoints
- [ ] < 480 px (switches to one-column layout)
- [ ] 600 px (changes bar chart layout from three column to accordion with one column)
- [ ] 768 px (converts side navigation from separate column to the right to a select list)
- [ ] > 768 (full site layout)

**Comment by mcharg** [comment]
Two issues, but I'm not sure whether either should hold up the release.

- [ ] Revenue by Company - Filters are missing at breakpoints below about 768 px.
- [ ] Reconclilation - The search appears to be defaulting to a search for "s".

**Comment by brentryanjohnson** [comment]
@mcharg The Reconciliation search issue is captured in #3732.

**Comment by mcharg** [comment]
@mentastc We should also add a similar issue for the FY revenue data file.  I've had issues with several fields in that that have extra spaces that mess up pivot tables.

**Pull request merged**
