### PR TITLE
updated packages

### LINKED ISSUE #2935: Review Security Vulnerabilities and Dependencies

### PR DESCRIPTION
**Pull request by master12**
Fixes #2935

Changes proposed in this pull request:

- Update package to update growl dependency
- Could not update the hoek dependency. Tables is the package that uses and old version of sqlite3 that causes the dependency on a old version of hoek. No way to update that dependency. Tables is used by our data generation scripts. Has zero impact on our live site. We can ignore this vulnerability.
- Please download locally and run build to test.

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@brentryanjohnson can you download locally to test? I don't have the rights.

**Comment by brentryanjohnson** [comment]
I'm still using Docker for local dev; @master12 If I pull down the branch, will my Docker instance pick up on these updates?

**Comment by master12** [comment]
Yes. It should thats why I want you to test it out

**Comment by jennmalcolm** [comment]
@master12 what do we need to do with the branch conflicts?

**Comment by master12** [comment]
resolved conflict

**Pull request merged**
