### PR TITLE
Applies content guidance to tribal section

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:deer: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/content-guidance-tribal/how-it-works/#native-american-overview/)

- Updates instances of "Indian" and "tribal" to "Native American" in accordance with our style guide and federal law
- Retains "Indian" and "tribal" when referencing specific legislation or tribe-specific content

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
Thank you, @mcharg! Just pushed some corrections.

**Comment by mentastc** [comment]
Is this how you want it to look? A few Indians there

image

**Comment by brentryanjohnson** [comment]
@mentastc Where did you find this?

**Comment by brentryanjohnson** [comment]
Never mind @mentastc, I found it. I'm not sure why it didn't show up in my search; thank you for finding it!

**Comment by jennmalcolm** [comment]
@brentryanjohnson since I merged the disbursements how it works content, this branch has conflicts. Could you look at that?

**Comment by brentryanjohnson** [comment]
@jennmalcolm Done.

**Pull request merged**
