### PR TITLE
Data validation 2

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/data-validation-2/)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Here is the correct preview branch https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/data-validation-2/. Please add reviewers @mentastc if this is ready.

**Comment by Maroyafaied** [comment]
This looks great. My only suggestion is to for the OGOR link to go to the onnr.gov page like the other links instead of the pdf form. This is the OGOR link on onrr.gov https://www.onrr.gov/ReportPay/production-reporting.htm

image
image

**Comment by lpgoldstein** [comment]
@mentastc would it be correct to add "of" between "All these" ? 
image

**Comment by jennmalcolm** [comment]
I'm going to merge as is, and if you see some edits that need to be made @lpgoldstein or @mentastc put in a PR for the next release.

**Pull request merged**
