### PR TITLE
Updated production and revenue monthly files

### LINKED ISSUE #3755: update monthly data- March
Update production and reveuen files wit hthe attached
[Production Volumes as of 3_5_19.xlsx](https://github.com/ONRR/doi-extractives-data/files/2937399/Production.Volumes.as.of.3_5_19.xlsx)
[monthly_revenue_02-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/2937400/monthly_revenue_02-2019.xlsx)

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #3755 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/update-monthly-data/)

Changes proposed in this pull request:

- updated the production data to November and the revenue data to February

### CODE REVIEW

**Comment by jennmalcolm** [comment]
When I tested copying and pasting the production data instead of replace the file, the production graphs worked. Should we merge that branch ([update-prod-graph](https://github.com/onrr/doi-extractives-data/commit/2198f654d031d30118e7f91d58fd993460d7dc2a)) into this PR?

**Comment by brentryanjohnson** [comment]
I recommend closing this PR and opening a new one with your working update, @jennmalcolm. I can open a separate one to update the downloads.

**Comment by jennmalcolm** [comment]
Ok @brentryanjohnson I didn't do the revenue graph update, but I'll add that to my branch and you can just do the downloads separately.

**Comment by brentryanjohnson** [comment]
Closing this PR and opening a separate, cleaner PR to update downloads files.

**Pull request closed without merging**
