### PR TITLE
Adds explanation for monthly and annual totals

### LINKED ISSUE #3384: Add scope and documentation to monthly production data
I've added the page and nav for monthly production data in #3377, but we need to add the scope and documentation.

We can't merge the PR until the content is there, so I'm leaving #3377 WIP until we finish the docs.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3384 

[:heavy_plus_sign: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/monthly-production/downloads/federal-production-by-month/)

Changes proposed in this pull request:

- Adds scope content to explain why 12-month production volumes may not add up to annual production volumes for respective commodities

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Just saw one typo:

image

**Comment by brentryanjohnson** [comment]
Great catch, @jennmalcolm. Thank you! It should be fixed with 👆 that commit.

**Comment by mentastc** [comment]
Should we also add this description to the production by year tab? I'll approve it but just something to think about.

**Comment by brentryanjohnson** [comment]
Good idea, @mentastc. #3435 documents your suggestion.

**Pull request merged**
