### PR TITLE
Changes 'Tribal' to 'Native American' in map legend

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:deer: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/content-guidance-legend/)

Changes proposed in this pull request:

- Changes map legend in Jekyll and GatsbyJS portions of site to conform to our style guidance and federal law

### CODE REVIEW

**Comment by mcharg** [comment]
I know this wasn't part of the change, but should we change it to "Federal lands and waters"? and "Other land (state, local, or privately owned)".  I don't know why this change made me notice more that "Other" is the only thing that doesn't say land and calling out waters would be consistent with the rest of the site and help explain the offshore zones.

**Comment by jennmalcolm** [comment]
@brentryanjohnson, I think @mcharg's suggested edits could add clarity and consistency. For the other category, I do think it would make more sense to have "land" outside of the parenthesis, but I'm thinking adding "owned" isn't necessary.

**Comment by mcharg** [comment]
I just noticed that federal has plural "lands and waters", but the others are singular "land".  Should we be consistent?

**Comment by brentryanjohnson** [comment]
@mcharg Yes, I was thinking about that, too. We have the same issue with "revenues" versus "revenue." I need to add some guidance to the content guide for both.

**Pull request merged**
