### PR TITLE
Gatsby version 2

### LINKED ISSUE #3728: Switch whole site over to Gatsby
This will involve making sure case studies need to be made static since those will not be updated.

### PR DESCRIPTION
**Pull request by master12**
Fixes #3728

[:sunglasses: PREVIEW]https://federalist-proxy-staging.app.cloud.gov/preview/onrr/doi-extractives-data/gatsby-version-2/)

Changes proposed in this pull request:

- Switching to gatsby v2
- Site can only be tested on Federalist staging see link above
- Offshore pages are static and will not work in preview mode currently please do not test.

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The selected page isn't bolding in the nav.

**Comment by mcharg** [comment]
@master12 The link to Revenue by Company on the homepage is returning a 404 error.
https://federalist-proxy-staging.app.cloud.gov/preview/onrr/doi-extractives-data/gatsby-version-2/how-it-works/federal-revenue-by-company/

**Comment by mcharg** [comment]
@master12 

- [ ] I get a 404 error if I pick a case study from the drop-down, but it works fine when picking from the map.

**Comment by master12** [comment]
@mcharg Dropdown doesnt have the preview url part please just verify the path is what /case-studies/%case study location%/ This will work in prod. Didnt want to add code since this is archive content.

**Comment by mcharg** [comment]
@master12 IE bugs:

- [ ] Revenue and disbursements bar charts on the homepage are displaying full width at a large viewport size.


- [ ] Case Studies map is tiny and missing some icons and has weird alignment on hover.

**Comment by mcharg** [comment]
@master12 Edge bugs:

- [ ] Same bug as above for IE with the revenue and disbursements charts being full width.
- [ ] Case studies map is large enough, but alignment is off on hover.

**Comment by Maroyafaied** [comment]
I got the 404 error clicking on this link
image

**Comment by mcharg** [comment]
@master12 iPhone bugs:

- [ ] Disbursements summary has an empty amount column on the right.

**Comment by brentryanjohnson** [comment]
FYI everyone...[Microsoft is moving Edge to Chromium](https://www.theverge.com/2018/12/4/18125238/microsoft-chrome-browser-windows-10-edge-chromium), which will probably mean that Edge-specific problems won't be as much of an issue in the future. Basically, Edge will be Chrome.

However, I haven't seen a timeline for the switch.

**Comment by brentryanjohnson** [comment]
> @master12
> 
> * [ ]  The selected page isn't bolding in the nav.
>   

There's a separate issue for this (#3738), as it's a problem that predates this PR.

**Comment by mcharg** [comment]
@brentryanjohnson In the current site it's just How It Works, but it's all the nav items in the PR.

**Comment by master12** [comment]
Ok bugs addressed:

- 404 errors
- scrolling to anchor links
- bolding menu

**Comment by jennmalcolm** [comment]
@master12 do we need to update this PR with the changes from our last release? The what's new is one release behind...

**Comment by jennmalcolm** [comment]
Are searches going to work in production? They give a 404 error on the preview. They also are not working (except for case study results) on the live site.

**Comment by brentryanjohnson** [comment]
There are some problems with search, even in production @jennmalcolm and @master12. For instance, a search for "gomesa" yields some odd results.

search results screen with search results are drawn from across this site, gomesa in the search field, and sorry, no results were found for your search, followed by try one of these popular searchs: energy, oil, gomesa

**Comment by jennmalcolm** [comment]
Yeah @brentryanjohnson the only search results I was getting in production were for case studies. So, I can create a new issue. I was just wondering if this PR is doing anything with searches.

**Comment by master12** [comment]
@jennmalcolm Yes we probably need to update what ever changes were made in the last release. The search is not hooked up yet.  I can remove the search. We can create a new issue to implement search on the site. We have options that I already discussed with Ryan.

**Pull request merged**
