### PR TITLE
3924 filterable url

### LINKED ISSUE #3924: Set up the filterable table url such that we can link to any given filtered view
This will come in handy for linking to revenue from state pages and allow us to send specific filtered views to stakeholders when they ask for a specific set of data.

### PR DESCRIPTION
**Pull request by master12**
Fixes #3924 

[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/onrr/doi-extractives-data/3924-filterable-url/query-data/?dataType=Revenue&landCategory=Onshore)

Changes proposed in this pull request:

- Added the ability to filer by Revenue, Production and Disbursements using the url for the query tool

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 I don't know how to review this without any link to the tool to see if they work.

**Comment by jennmalcolm** [comment]
This works for the data type, but is it supposed to work for other seletions @master12? It seems like your preview URL is also supposed to select onshore, but that part doesn't work.

**Comment by jennmalcolm** [comment]
Actually, I guess it is filtering the data down to what the url shows, but it just doesn't show anywhere besides the URL what it has been filtered down to (e.g. the land category dropdown still says "select". Can we change that?

**Comment by master12** [comment]
We cant change the toolbar selection at this time but will work on a solution in the future. There are now 2 links:
1. How it works -> Native American Revenue
2. How it works -> Native American Production

**Comment by mcharg** [comment]
@master12 Can you at least make the drop-down show that Native American is selected for the land category?  Right now, there's nothing indicating that it's showing only Native American production, so the user would have no way of knowing this isn't all production.

image

**Comment by master12** [comment]
No I cant

**Comment by master12** [comment]
removed the native american links so we can keep the code but not use it yet

**Comment by mcharg** [comment]
@master12 The links are still showing up for me.

**Comment by jennmalcolm** [comment]
@mcharg it seems ok to me since the links under how it works, Native American production and revenue just take you to the query tool to fill out your selections, but I"m not sure if I know what links still need to go away.

**Comment by mcharg** [comment]
@jennmalcolm I thought we were getting rid of the links altogether, but I guess it's fine the way it is.

**Comment by jennmalcolm** [comment]
Ok @mcharg, thanks. I think it doesn't hurt to have a link to where they can get to the data since the data isn't on the how it works sections now.

**Pull request merged**
