### PR TITLE
4121 refactor revenue

### LINKED ISSUE #4121: Refactor revenue data update

### PR DESCRIPTION
**Pull request by master12**
Fixes #4121

[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/onrr/doi-extractives-data/4121-refactor-revenue/)

Changes proposed in this pull request:

* please review revenue numbers.

- Added revenue data from excel files
- Updated explore data, state pages and how it works/native american revenue tables
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mentastc I'll start with checking the Native American revenue and the revenue filterable table.

**Comment by Maroyafaied** [comment]
@master12 are the combined files supposed to show in the downloads? It's still showing the Native American files as separate.

**Comment by Maroyafaied** [comment]
@master12 the homepage revenue charts for CY 18 offshore is not matching the number on the combined file.

image
image

**Comment by jennmalcolm** [comment]
@Maroyafaied, regarding the downloads pages, we will need to have #4126 done before we can get rid of the separate downloads files. The goal is to have the same file (the consolidated one) as the source for all revenue data and the download, but I guess there's no need for you to review the downloads at this time. I'm sorry that I led you in the wrong direction on that.

**Comment by Maroyafaied** [comment]
@master12 the revenue table is not matching the combined FY files when you select all land category but it does match when you break out the land category.

image

image

**Comment by Maroyafaied** [comment]
I checked the homepage chart, the Native American revenue tables, and the revenue filterable table. The Native American revenue tables looks good but I found issues in the homepage chart (CY18) and the filterable revenue table.

**Comment by mentastc** [comment]
The explore data national level revenue data is displaying Native American and Federal Revenues but should only be Federal.
image
image

**Comment by mentastc** [comment]
@master12 , when I click on an offshore region I get this page:
image

**Comment by mentastc** [comment]
State level explore data pages match the expected revenues.

**Comment by jennmalcolm** [comment]
@master12 should we look at this PR again? I see that you made some more commits last week. Is it ready for another review?

**Comment by master12** [comment]
@jennmalcolm Yes please review production and revenue

**Comment by jennmalcolm** [comment]
@mentastc and @lpgoldstein could you please check data again?

**Comment by lpgoldstein** [comment]
@master12 It looks like the excel file for monthly revenue has been updated since this pull request - the preview shows data through April, but we already have June data live on the site. Do you want me to fix this  (@brentryanjohnson said he would help me)?

**Comment by mentastc** [comment]
The Revenue filterable table only goes back to 2006 but the data set goes back to 2003.
image

**Comment by mentastc** [comment]
The Explore data page is still showing Federal and Native American Revenues when it should be just federal, also the revenue downloads page is a download for federal and native american revenues which is fine but on the page it references it as federal only.

**Comment by jennmalcolm** [comment]
@mentastc it should be fine to keep the download file as is because you and @brentryanjohnson will be addressing the text in #4126 this sprint. You can just use the federal page as the basis for your consolidated page.

**Comment by mentastc** [comment]
@master12  Looks like the downoad page is ok and Ryan and I will update that,  but we need to fix the explore data revenue section since it's pulling in Native American

**Comment by master12** [comment]
Closing this request due to these changes will be in another PR

**Pull request closed without merging**
