### PR TITLE
Use consistent title for leasing in revenue phase tables

### LINKED ISSUE #3745: Change titles of revenue by phase to be consistent
As I was going through the different pages for rates, I noticed  revenue phase1 is titled differently in the how it works page and the explore data page.

image

image

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3745

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/consistent-process-table/explore/#revenue)

Changes proposed in this pull request:

- Changes copy in revenue table to match that of how-it-works process table

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@brentryanjohnson I get a 404 error when I open the link

**Comment by brentryanjohnson** [comment]
@Maroyafaied Federalist builds are failing right now. @master12 is looking into it.

When the `federalist/build` status changes from ❌ to ✔️, it will be ready to review. We'll probably have to try to rebuild a few times for that to work, though.

Status of build checks, including failed status for federalist staging build, federalist build, and circle ci build

**Comment by master12** [comment]
This has built federalist is not updating the status properly. Please review @Maroyafaied

**Comment by Maroyafaied** [comment]
@brentryanjohnson it seems like when I created the issue #3745, we had different titles for the phases in the how it works revenue streams and rates table than we do now.  What we have now for phases is "bonus , rent , royalty". Before, we had "securing lease or a claim, before production, and during production".  So I think leaving the explore data table with the title of "securing rights" for the first phase on both tabs is fine, and there is no need to change it to "securing a lease or claim". 
image
image

image
image

**Pull request closed without merging**
