### PR TITLE
updates monthly production

### LINKED ISSUE #4856: Update Production and Revenue Data
- update revenue data on website through November 2019
- update production data on website through August 2019

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #4856 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/updateagustproduction/)

Changes proposed in this pull request:

- updates monthly production file

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@brentryanjohnson it looks like it failed to build, do you know the reason why? Thanks

**Comment by brentryanjohnson** [comment]
@Maroyafaied It threw an error related to an Excel id.

```
 ERROR #11321  PLUGIN

"custom-excel-transfomer" threw an error while running the onCreateNode lifecycle:

Cannot set property 'id' of [FILTERED]
``

Did you try the data scripts to check the file?

**Comment by brentryanjohnson** [comment]
@Maroyafaied Here's the output from our diff script:

```
New Rows: [1112, 1113, 1114, 1115, 1116, 1117, 1118]
Dropped Rows: []
Changed Cells: []
New Columns: [datetime.datetime(2008, 1, 31, 0, 0), 'Federal', 248400296.794714, '2008-01-31 00:00:00.1', 'Gas Prod Vol (mcf)', 'Offshore']
Dropped Columns: ['Land Category', 'Volume', 'Commodity', 'Month', 'Land Class', 'Calendar Year']
```

**Comment by brentryanjohnson** [comment]
It looks like the new file is missing column headers, for one thing.

**Comment by Maroyafaied** [comment]
@brentryanjohnson thank you, I'll go fix it.

**Comment by Maroyafaied** [comment]
I deleted this branch and started over, sorry about that. I will close this one and send a new pull request soon.

**Pull request closed without merging**
