### PR TITLE
Monthly Revenue and Production (March)

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/monthly_revenue_production_march_2020_2/)

Changes proposed in this pull request:

Production Monthly (monthly_production)	
- [x] Homepage: monthly bar charts
- [x] Homepage: CY bar charts
- [x] Homepage: FY bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Homepage: CY bar charts
- [x] Homepage: FY bar charts
- [x] Homepage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

-
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@mentastc and @Maroyafaied I checked everything except for the fiscal year charts.

**Comment by jennmalcolm** [comment]
@Maroyafaied could you take a look at this PR? Thanks

**Comment by Maroyafaied** [comment]
The dates for production monthly should be 11/2019 
image

**Comment by Maroyafaied** [comment]
The dates on revenue monthly should be 2/2020 . Also the units in FY production is duplicated. 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied can you commit the changes to this branch to fix the dates? The double units problem already exists on the site, and we're not addressing it now since we should be moving to the new site soon.

**Comment by Maroyafaied** [comment]
@jennmalcolm I corrected the dates.

**Pull request merged**
