### PR TITLE
Monthly Production and Revenue Update

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/monthly_revenue_production_january_2020/)

Changes proposed in this pull request:

Production Monthly (monthly_production)	
- [x] Homepage: monthly bar charts
- [x] Homepage: CY bar charts
- [x] Homepage: FY bar charts
- [ ] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Homepage: CY bar charts
- [x] Homepage: FY bar charts
- [x] Homepage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@mentastc the production data for october is showing as 2020 rather than 2019.

**Comment by mentastc** [comment]
@lpgoldstein  I fixed the csv and xlsx, dumb mistake. Thanks for the catch.

**Comment by Maroyafaied** [comment]
@mentastc the file sizes for the production monthly files are not correct, I think it should be 57 KB for the excel and 74KB for the csv 
image

**Comment by Maroyafaied** [comment]
@mentastc the production file sizes still need to be corrected.

**Comment by jennmalcolm** [comment]
@mentastc do you want me to merge this or close it and you can do a PR with the new data we received? I want to do a release today to refresh the data one way or another, so if you need more time to check the new data, we can merge this, but first please change the file sizes. I checked, and the numbers from @Maroyafaied  look right to me.

**Comment by jennmalcolm** [comment]
@Maroyafaied the sizes should be fixed now

**Comment by Maroyafaied** [comment]
@jennmalcolm I still see 287KB and 429KB instead of 57KB and 74KB

**Comment by jennmalcolm** [comment]
@Maroyafaied use this preview link: https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/monthly_revenue_production_january_2020/

**Pull request merged**
