### PR TITLE
Add home page gatsby (WIP)

### LINKED ISSUE #3293: Build home page in Gatsby

### PR DESCRIPTION
**Pull request by master12**
Fixes #3293
* Currently a work in progress but wanted to share with the team.

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/add-home-page-gatsby/)

Changes proposed in this pull request:

- Replaced old home page with new design
- Includes updated and added components
-

### CODE REVIEW

**Comment by mcharg** [comment]
We need to have a minimum amount of padding between the charts (10px), so they never bleed together like this.
image

**Comment by mcharg** [comment]
Period drop-down should be left aligned when we get to one column view.  It's currently indented.
image

**Comment by mcharg** [comment]
Colors need to be updated.

Selected:
Darkest: #086996 $blue-dark
Medium: #79BBDA $blue-mid
Lightest: #C6E9FF $blue-cthru

Hover:
Selected color with 80% opacity

Unselected:
Darkest: #4E4E4E
Medium: #A9A9A9
Lightest: #E0E0E0

**Comment by mcharg** [comment]
Hover functionality needs to be added.

**Comment by brentryanjohnson** [comment]
In accordance with our content guide, subheadings should be sentence case. So "What's New" should be written as "What's new".

what's new section on homepage

**Comment by mcharg** [comment]
@brentryanjohnson We probably also need a process for updating the "What's new" content for each release.

**Comment by brentryanjohnson** [comment]
I agree, @mcharg. We have the release notes in GitHub, but that audience is different from the "What's new" audience. So I don't think we should replicate the release notes for that section. I can add guidance for it in the wiki, but I think we're generally aiming for:

- updated data
- updated visualizations
- contextual narrative additions

Basically, things users can see.

Trickier examples are things like "Revised search results," which is borderline, to me. We could always try listing the main features and updates and link to the release notes for a more in-depth summary of changes. That way we can potentially meet both audiences' needs.

**Comment by mcharg** [comment]
@brentryanjohnson I like the idea of keeping it simple and contained to things users can see and then linking to the full release notes.

**Comment by jennmalcolm** [comment]
I think that is a good plan @brentryanjohnson. Are you going to draft up something for this first version of the what's new section? Please add some guidance in the wiki. It seems like we could make updating that section, or at least evaluating it to see if it needs updates, part of our release process.

**Comment by brentryanjohnson** [comment]
This is perhaps minor compared to the heavy lift of coding @master12 is doing here, but the banner looks awkward to me with the rig floating in the air. The spacing is unequal as well, with excess space below the links, and contraction above the paragraph.

More importantly, the tabs show up and then disappear, but I'm guessing that's a known issue.

## As built
image

## Proposed
feature image grounded to bottom

**Comment by mcharg** [comment]
Feedback on the tabs:

- There shouldn't be a bottom border on the selected tab.
- There's a white background on the icon on the Explore the data button.
- I'm okay with Ryan's suggestion to ground the oil rig image.
- On the one column view, the line under the "Explore [section name] data" header should extend the full width of the column.
- See comment in #3287 for changes to a few of the explore links until we get the split up explore data page.

**Comment by mcharg** [comment]
Here's the icon without the circle around it.
[WhiteChartNoCircle.zip](https://github.com/ONRR/doi-extractives-data/files/2538703/WhiteChartNoCircle.zip)

**Comment by master12** [comment]
@mcharg Your WhiteChartNoCircle icon is not showing up properly

**Comment by master12** [comment]
@mentastc @brentryanjohnson @jennmalcolm @mcharg Please do another review of the home page. Data added and several issues resolved .

**Comment by mcharg** [comment]
Tabbed section:
- Download links have the wrong icon (see previous comment for the icon)
- All the links lose their icons when it goes to the one column view
- @brentryanjohnson Will the new disbursements content be there when this goes live?  If so, we should link to that from the disbursements tab button.
- Revenue by commodity link should link to the "Federal revenue trends by resource" section.
- I'm getting a 404 error on the revenue downloads link

Data Summary
- The production charts are still too wide on 320px.  Revenue and Disbursements are working right.
image
image


- When in the 1 column view, the chart should extend the full width.  Here, it should be as wide as the title.
image

- Need more padding below the "show details" link.  You can use the same amount as is between the period drop-down and the chart title.
image
- Left align the period drop-down with its label.
image
- The tables below the charts are supposed to change to the numbers associated with the hover bar year on hover and the key swatches should change to the hover color when doing that.
- On the monthly table, the month name is missing from the column header.
- The "($)" isn't needed on the Revenue and Disbursements table headers.

**Comment by brentryanjohnson** [comment]
This is looking great, @master12.

A few things:

- It's missing the mobile nav menu, which `explore` and `about` are missing as well (#3349)
  - I don't believe there is a component built for this yet
- We need a margin between the production section and the revenue and disbursements section (`4rem` separates them nicely)
- None of the subtext sentences (e.g., "Production data for major commodities") should have punctuation, because they are incomplete sentences. Just remove the periods from each instance (Production, Revenue, Disbursements)
- Map legend should include changes reflected in #3351 
- The main navigation and tab navigation is crowded; we should add space between (which we can do later, if needed)
- The toggle to monthly shows "undefined" for the most recent year, probably due to the monthly toggle not applying to disbursements
  - It also results in "undefined" for the production charts when toggled for revenue
revenue and disbursements chart

oil, gas, and coal charts

**Comment by mcharg** [comment]
Firefox issues:
- Explore Data button is wonky.
image

**Comment by mcharg** [comment]
Also wonky in IE.
image

**Comment by mcharg** [comment]
Other IE issues:
- Toggle to monthly view doesn't work.
- Broken tabs
image
-

**Comment by mentastc** [comment]
When you click on a year it doesn't change to that year in other charts this happens in other areas of the site. 

image

**Comment by mcharg** [comment]
@mentastc It's only supposed to change the others within production, but not for revenue or disbursements.

**Comment by mcharg** [comment]
@brentryanjohnson pointed out another issue.  We shouldn't put a year into the annual graphs until it's completed, so those bars are apples to apples.  @jennmalcolm Should we remove 2018 from the yearly graphs or change them to be fiscal year (which would make everything consistent, since disbursements is only fiscal year)?

@brentryanjohnson We're also missing content that says whether these are fiscal or calendar year.  Should we put that in the intro paragraphs or the table header row?

**Comment by jennmalcolm** [comment]
@mcharg, I would prefer to keep the default as calendar year and remove 2018. I think an average non-federal government user would find calendar year more meaningful.  We don't have FY 2018 production data yet anyway. We should be clear that disbursements is for fiscal year and the others are calendar. I guess once we have monthly data for disbursements, we could be consistent and offer calendar year too. That is something we can consider later. Another option to possibly roll out later would be to provide a drop down like we do for the monthly data where users can pick if they want to see the annual data for calendar or fiscal year.

**Comment by mcharg** [comment]
Remove 2018 from the yearly view for production and revenue.

- [ ] Fixed

- [ ] Tested

**Comment by mcharg** [comment]
Add calendar/fiscal year indicator to yearly view.
https://u7sqr1.axshare.com/#g=1&p=home

- [ ] Fixed

- [ ] Tested

**Comment by mcharg** [comment]
Put 2018 back in for disbursements.

- [ ] Fixed

- [ ] Tested

Fix yearly table headers to display the year again instead of "calendar year" or "fiscal year".

- [ ] Fixed

- [ ] Tested

**Comment by brentryanjohnson** [comment]
I noticed the mouse state on hover over the yearly/monthly tab is a text cursor. We should change this to a pointer state.

- [ ] Fixed
- [ ] Tested

**Comment by mcharg** [comment]
Looking good, @master12! 

Below is a summary of open issues (includes all open things from above comments).

# Show stoppers: Should be fixed before launching
Need to add onshore/offshore category to disbursements chart.

- [ ] Fixed

- [ ] Tested

Disbursements button is going to a 404 error page.  Do we need to merge with @brentryanjohnson's PR that adds that page?  Also, the button text can change to "How disbursements work" now that it's not linking to the budget process.

- [ ] Fixed

- [ ] Tested

Menu button is still missing from mobile.
- [ ] Fixed

- [ ] Tested

Toggle to monthly view is still broken in IE.
- [ ] Fixed

- [ ] Tested


# Minor changes: Nice to have, but not show stoppers
On hover, the swatches in the table should change to the hover color.

- [ ] Fixed

- [ ] Tested

Table header for the month should have the year after the month name. (e.g. Mar 2018)

- [ ] Fixed

- [ ] Tested

Production charts aren't moving together on click.
- [ ] Fixed

- [ ] Tested

Could use a but more space between the primary nav and tabs are crowded.
- [ ] Fixed

- [ ] Tested

**Comment by jennmalcolm** [comment]
This is looking good @master12. I'm excited and hoping we can release today or tomorrow. I also noticed one other issue, and I'm not sure if you've already discussed it. When I click on one of the states, from the map, it takes me to a page with the state links and nothing else (like the data).

**Comment by jennmalcolm** [comment]
@master12 if you haven't worked on it already, hold off on creating the onshore/offshore category. We got some numbers for Maria, so when @mentastc gets in, we can update the spreadsheet so that we don't have that problem any more.

**Comment by brentryanjohnson** [comment]
I noticed the viewport that's roughly tablet-sized and introduces the hamburger menu tends to cramp the wordmark and the "tabordion." 

homepage layout with insufficient space between wordmark and tabs

**Comment by mcharg** [comment]
Links to Native American production and revenue are broken because they changed with the change from Indian to Native American.

New production link: https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/add-home-page-gatsby/how-it-works/native-american-production/#production-on-native-american-land
New revenue link (which I just noticed is missing): https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/add-home-page-gatsby/how-it-works/native-american-revenue/#revenue-data

- [ ] Fixed

- [ ] Tested

**Comment by mcharg** [comment]
Getting a 404 error on links to offshore region pages from the map.
image

- [ ] Fixed

- [ ] Tested

**Comment by mcharg** [comment]
The tabordion and menu are no longer displaying on my iPhone.  They display fine on my Android.
image-1

- [ ] Fixed

- [ ] Tested

**Comment by mcharg** [comment]
The charts are also missing on iPhone, but display fine on Android.
image-1 1

- [ ] Fixed

- [ ] Tested

**Comment by Maroyafaied** [comment]
The map doesn't show colors on internet Explorer 
image

**Comment by mcharg** [comment]
Revenue by Company link is taking you to Native American Revenue.  We need to add a link to Native American Revenue under the By Company link.

- [ ] Fixed

- [ ] Tested

**Comment by jennmalcolm** [comment]
@master12 the revenue by company link should go here: https://revenuedata.doi.gov/how-it-works/federal-revenue-by-company/2017/

It is going to the Native American revenue section now. @mcharg I don't think there is a place in the design to use that link for the Native American revenue. Maybe we add this in a future iteration?

**Comment by mcharg** [comment]
@jennmalcolm There was a note in the issue with the links for the interim version to add the link the Native American Revenue under the By Company link.

**Comment by brentryanjohnson** [comment]
☝️ Two commits should fix company revenue link and add Native American revenue.

**Comment by mcharg** [comment]
The disbursements link is right, it just stops scrolling here:
image

**Comment by mcharg** [comment]
Right now, the only thing keeping me from signing off on the build is the iphone issue where revenue and disbursements are 50% width.

**Comment by jennmalcolm** [comment]
The 2017 disbursements number is wrong. I tracked down the problem and the spreadsheet had both "offshore" and "Offshore". The numbers with "offshore" were not counted. I changed the Google Drive data file to make the capitalization consistent, but that will need to be updated.

**Comment by brentryanjohnson** [comment]
I submit that the colons are unnecessary in a table layout. I propose we remove them, as they add more messiness than clarity.

table layout showing native american, offshore, and onshore data for oil, gas, and coal

**Comment by master12** [comment]
@mcharg @jennmalcolm The Iphone issue was resolved on my macbook. Hopefully it works on Shannon's iphone and we can release this bad boy. I wil check my email tomorrow to see if you have any issues left.

**Comment by jennmalcolm** [comment]
yes, @master12 it is fixed on my iphones. Thanks!

**Comment by jennmalcolm** [comment]
@mentastc those are the dates that are updated now. We can update the dates next sprint. @master12 is off today too. Hopefully he can show the rest of the team how to update the numbers since we will need to do these monthly. @mentastc I would also like you to document and share with the team where the most recent versions of the data are officially stored and we can evaluate if we need to make any changes to our storage procedures as part of our current effort to standardize our data formatting and review procedures.

**Comment by mcharg** [comment]
@master12 the iPhone issue is fixed on my phone!

@jennmalcolm the map issue has been a problem for a while and isn't new in this release.  See #3237 and #3206.

**Comment by jennmalcolm** [comment]
I'm going to merge, and the next round of reviews and approvals can happen in the release PR.

**Pull request merged**
