### PR TITLE
Adds design pattern to archive content in place

### LINKED ISSUE #2863: Create archive for EITI content that will no longer be maintained
Part of #2799.

- Relocate (or archive in place) USEITI-specific content that is unlikely to be maintained in the future
- Develop unobtrusive design pattern to indicate archived content and succinctly communicate to users why the content has been archived

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #2863 and #2722

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/)

This is a work-in-progress PR that adds a design pattern for EITI-specific content that will no longer be maintained.

I'm pushing the PR to invite feedback on the patterns.

### CODE REVIEW

**Comment by jennmalcolm** [comment]
I like the banner. Can you make a different size one for the case studies so that it doesn't overlap with the maps?

**Comment by brentryanjohnson** [comment]
@mcharg I am basing the patterns on #2863, but there are some issues with those design prototypes in certain instances. I'm still working on it. Perhaps we can schedule some coworking time.

**Comment by mcharg** [comment]
@brentryanjohnson I got that. Take a look at the comments I added to the issue.

**Comment by brentryanjohnson** [comment]
@jennmalcolm and @mcharg [Please have another look at this](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/case-studies/campbell/). This should fix the collision issue of the archive banner and the case studies maps. 

All "content" pages share the same template, so I originally had the archive banner `include` in the case studies markdown for each respective case study, but that caused the collision. Rather than create a duplicate banner with a constrained width, I added conditional logic to the content template to target the case studies pages.

```
{% if page.permalink contains '/case-studies/' %}
      {% include archive-banner.html %}
{% endif %}
```

**Comment by jennmalcolm** [comment]
looks good @brentryanjohnson

**Comment by brentryanjohnson** [comment]
I should note that I'm intentionally using the passive voice for this archive banner, in large part for (1) tense reasons and (2) distance, because while ONRR manages revenue, disbursements, and the data that results, it was a administration-level decision to withdraw from EITI.

**Comment by brentryanjohnson** [comment]
I remove the WIP flag; please review this again @mcharg and @jennmalcolm and let me know your thoughts.

I didn't match all prototype styling, but I hope these are reasonable alternatives for transitional styling. I can also continue to iterate on them in the next sprint.

- [Downloads-->Reconciliation](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/downloads/#reconciliation)
- [How it works-->Reconciliation](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/how-it-works/reconciliation/2016/)
- [Case studies landing](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/case-studies/)
- [Case study, Wyoming (for example)](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/case-studies/campbell/)
- [About-->Executive summaries](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/about/report/)
- [How it works-->Audits and assurances](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/how-it-works/audits-and-assurances/#tracking-and-verifying-payments)
  - This one removes the button styling and converts the link to plain text on account of styling collisions

**Comment by mcharg** [comment]
@brentryanjohnson How it works > Reconciliation feels weird having the message above the breadcrumbs (which should always be the first thing on the page).  Any way to fix that?

I think all the other versions work.

**Comment by brentryanjohnson** [comment]
Agreed, @mcharg. This one is tricky, because of the columns and the year tabs at the top. The initial placement spans the columns, which is why I placed it there. It doesn't sit well in the left column below the breadcrumb, but the right column might work. Thoughts?

## Left column
reconciliation banner left

## Right column
reconciliation banner right

**Comment by mcharg** [comment]
@brentryanjohnson I like it in the right column.

**Comment by brentryanjohnson** [comment]
Okay, @mcharg. The [new commit places](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/how-it-works/reconciliation/2016/) it in the right column.

**Pull request merged**
