### PR TITLE
How the LWCF and HPF work

### LINKED ISSUE #3054: Write explanatory content for LWCF and HPF appropriations process
The disbursements process for the Land and Water Conservation Fund and the Historic Preservation Fund are distinct from the disbursement process for states, the Treasury, etc., in that the amount disbursed is subject to congressional appropriation.  

We should draft content in the How it works section to explain this process, so we can include the actual amount appropriated to the respective funds versus the amount ONRR disbursed to the funds.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3054

[:evergreen_tree: Land and Water Conservation Fund PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/how-funds-work/how-it-works/land-and-water-conservation-fund)

[:school: Historic Preservation Fund PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/how-funds-work/how-it-works/historic-preservation-fund)

Changes proposed in this pull request:

- Adds contextual content for the Land and Water Conservation Fund and Historic Preservation Fund (elsewhere we are adding actual annual congressional appropriations alongside the disbursed amount)
- Also adds two new terms to the glossary in this PR and in the [Gatsby explore data PR](https://github.com/ONRR/doi-extractives-data/pull/3106/commits/1b5c9b797481b43d13c290d83765e7f8793b4edb)
  - "8(g)"
  - "Authorization"
- Corrects existing summary content of congressional appropriations to the LWCF since 1999

Most content on the web for these funds is either too broad for our scope or too narrow. We needed an overview focused on the funding and appropriations process for these funds, which is why I researched and wrote this content.

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
I'm pulling the work in progress flag from this pull request. Please review the content when you have a chance, @jennmalcolm and @Maroyafaied.

**Comment by brentryanjohnson** [comment]
Next step: change links in [Gatsby explore data page](https://github.com/ONRR/doi-extractives-data/pull/3106/commits/1b5c9b797481b43d13c290d83765e7f8793b4edb) to go to these new pages instead of existing content.

Disbursements summary

**Comment by brentryanjohnson** [comment]
Thank you, @Maroyafaied. I've responded to your link questions below.

## Link questions

### American Battlefield Protection Program
We do have a [link to the American Battlefield Protection Program in this section](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/how-funds-work/how-it-works/land-and-water-conservation-fund/#distribution-of-funds).

### Land acquisition data
The strategy here is to link to general resources, not specific ones, and ideally not PDFs. The goal is to link to landing pages that have up-to-date links, rather than finding those links every year (or more often) to update them. Because PDFs are not responsive, we try to avoid linking to the data or content in that format, if we can avoid it. If there's a better landing page to link to, I'd be happy to change the link.

### State and local grant funding
I considered linking to this page in the relevant section, but it doesn't appear to be completely up to date. It does provide solid background information, though, so I'll push a version linking to it. 👍 

### Cooperative Endangered Species Conservation Fund
We'll retain the archived data that we currently have, so this will still be there. But yes, we should add a mention in this contextual narrative. I'll push an update. 👍 

### Congressional Research Service report
This report is excellent, and I referenced it while writing the content. I don't have a problem linking to it, but I'd rather find a government resource to link to (this link is to www.everycrsreport.com, which isn't a government resource). The Congressional Research Service apparently has a website (www.crs.gov), but it isn't loading for me. There's also a [2018 update to this report](https://fas.org/sgp/crs/misc/RL33531.pdf), but the link is non-governmental as well. Let's see if we can track down a government source for this report, so we're not linking to an organization that may have special interests.

**Comment by Maroyafaied** [comment]
thanks for explaining @brentryanjohnson , also I forgot to mention the Historic Preservation Fund page has a  glossary link that doesn't work, I'm not if it's meant to be there
image

**Comment by brentryanjohnson** [comment]
@Maroyafaied The link _is_ meant to be there, and it _is_ meant to work. What happens when you click it? It's a new glossary entry, so that could be part of the problem, but it's working fine on my end.

**Comment by Maroyafaied** [comment]
@brentryanjohnson never mind it worked, I was clicking on the book icon and nothing happens when you do that but when I click on the word  authorized it works.

**Comment by brentryanjohnson** [comment]
@Maroyafaied Yes, that's a bug we're trying to fix in the new codebase. We've observed in user research some usability problems with that icon not triggering the glossary link.

**Pull request merged**
