### PR TITLE
Dev-->master

### PR DESCRIPTION
**Pull request by jennmalcolm**
This is a big PR that includes the data update refactoring. We are missing the archive in dev, so we will have to get that fixed before we merge, but I wanted the team to get started reviewing this PR since there is a lot to check.

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Refactored data update process for annual production and revenues and updated data through 2018
- Build offshore pages in Gatsby
- Updated monthly revenue and production data
- Consolidated revenue downloads pages for federal and Native American
- Moved land ownership content on state page templates
- Added conditional logic to provide glossary link in search results only when the term is in the glossary
- Published blog article on going beyond open data
- Added June disbursements download file

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Things to check:

Navigate between pages
- [ ] Check several types of location profile page to ensure data and liquid templates are working as expected
- [ ] Check links are working correctly
- [ ] Check drop downs menu and validate they work 

Text
- [ ] No misspelling
- [ ] Correct spacing
- [ ] Correct format
- [ ] Accurate dates displayed

Revenue choropleth county maps on state pages
- [ ] Appears on the page
- [ ] Shaded correctly
- [ ] county/offshore area maps: hover behavior and do detail tables open

Data [Detailed instructions (limited access) ](https://docs.google.com/document/d/1ypXgw9yEETx9T-ZlDOTULeysaws3qKsfRLV6mOygB3I/edit)
@lpgoldstein and @Maroyafaied I know this is a double check from what you did on the PR, but could you look at these items to verify the data again before we release?
- [ ] Homepage bar chart data - revenue and production - monthly and FY and CY
- [ ] Revenue trends data
- [ ] Revenue filterable table data
- [ ] Native American revenue data
- [ ] Explore data CY revenue data - bar charts and megachart
- [ ] Explore data CY production data - bar charts
- [ ] State/offshore page production data
- [ ] State/offshore page revenue data
- [ ] Downloads files

Check all browsers
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

**Comment by Maroyafaied** [comment]
I reviewed homepage charts, state/offshore production and revenue and download files. All look good

**Comment by mcharg** [comment]
The links all work in the blog post and I didn't notice any typos.  I do think it's weird that we're linking to an external slideshare about hypothesis driven design, when we have a page on our wiki with our user-centered design process. https://github.com/ONRR/doi-extractives-data/wiki/User-Centered-Design-Process

**Comment by mcharg** [comment]
On the county maps, what does white mean if the lightest blue includes 0?
image

**Comment by mcharg** [comment]
I checked to make sure the new functionality works in a variety of browsers.  I didn't check every link or any data.

**Comment by lpgoldstein** [comment]
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/explore/revenue/

image

**Comment by master12** [comment]
Ok I think I fixed the issue.

**Comment by mcharg** [comment]
@master12 It's working in Chrome, Edge, and Firefox.

**Comment by lpgoldstein** [comment]
It's working on iPhone Safari as well

**Comment by lpgoldstein** [comment]
I'll check through all of the links and look for spelling type stuff.

**Comment by mcharg** [comment]
I really like how the map came out on mobile and I think it should stay clickable.  I'm not having trouble with accidentally clicking while scrolling on my phone and can pinch to zoom in on smaller states.

**Comment by Maroyafaied** [comment]
It there supposed to be a map icon on top of the navigation menu like we currently have for state/offshore pages? 
image

image

**Comment by mcharg** [comment]
@master12 The map icon was in the same release as the archive.  Maybe that whole release isn't there?

**Comment by master12** [comment]
Archive is BACK!

**Comment by mcharg** [comment]
We should probably create a new issue to get the state map back in the nav or re-open the old one, but it shouldn't hold up release.

**Pull request merged**
