### PR TITLE
Adds USEITI archive page to Gatsby

### LINKED ISSUE #3651: Migrate archive to Gatsby
Our [new archive](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/archive/archive/) is built in Jekyll. We need to migrate it to Gatsby.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3651

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/archive-page/archive)

Changes proposed in this pull request:

- Adds archive page to Gatsby, using "how-it-works" layout
- Refactors and reduces content on [`about` page](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/archive-page/about) to move USEITI detail to archive
- Changes link in archive banner to go to archive landing (instead of `about`)
- Changes main navigation link from `Case studies` to ` Archive` (Case studies is part of the archive)

_We still need to do something about archiving opt-in state content, but that's a larger scope of work than this._

### CODE REVIEW

**Comment by jennmalcolm** [comment]
This is looking good. You've accomplished a lot already. The links in the Economic Impact section are just going back to the top of the archive section.

Also, what would you think of adding a navigation component to the archive page since we have multiple headings in there?

**Comment by mcharg** [comment]
@brentryanjohnson I thought we decided to put the archive on the About page and move About to the last item in the navigation.  With them separate, it's too much in the primary nav that distracts from primary user tasks. If you want to keep it a separate page, how about having it live in the footer rather than the primary nav?

**Comment by brentryanjohnson** [comment]
We had talked about that, @mcharg, but I considered adding it to the nav for a period of time to let users know it exists. 

I can pull it, though. Now that we have search back, users should be able to get to everything fairly easily.

**Comment by brentryanjohnson** [comment]
I had the navigation component in the template, @jennmalcolm, but it was breaking the build for some reason. I pulled it to try to get the rest of the page built, but I'll revisit it.

**Comment by jennmalcolm** [comment]
I think it would be good to have archive on the Nav, at least for a while, in case people are looking for something like the case studies that used to be easily accessible. It seems like the archive link would be a more intutive place to go for stuff that has disappeared than the about page.

**Comment by brentryanjohnson** [comment]
@jennmalcolm I noticed some styling issues I still need to take care of. I'll let you know when complete.

**Comment by brentryanjohnson** [comment]
It should be good to go now, @jennmalcolm

**Comment by mcharg** [comment]
@brentryanjohnson The TOC is covering up content on mobile, otherwise it looks good.
image

**Comment by mcharg** [comment]
For the timeline, can the executive summary links link to the section for the appropriate year instead of all going to the top of the executive summaries page?

**Comment by brentryanjohnson** [comment]
Have another look when you have a chance, @mcharg.

**Pull request merged**
