### PR TITLE
Explains tickets/pounds

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[🔮 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/tickets-pounds/explore)

Changes proposed in this pull request:

- Adds glossary term for `tickets/pounds`
- Adds documentation question for `tickets/pounds`

### CODE REVIEW

**Comment by mcharg** [comment]
@brentryanjohnson Don't forget to add the link to the glossary from the bar chart:
image

**Comment by brentryanjohnson** [comment]
@mcharg It's supposed to loop through and add it automatically. I think the `/` might be preventing it from doing so, but I'm looking into it.

**Comment by Maroyafaied** [comment]
@brentryanjohnson should the state page of Arkansas have a link for the bar chart as well? 
image

**Comment by brentryanjohnson** [comment]
@Maroyafaied Yes. I'm still working on the glossary link issue.

**Comment by brentryanjohnson** [comment]
@Maroyafaied and @mcharg The unit should have the glossary term behavior, when it finishes building.

**Comment by mcharg** [comment]
@brentryanjohnson Ok.  I was going to wait for Nadia to find the lease and provide her feedback before approving, but I think what you have is fine if you want to get something out there in case it takes a while to find the lease.

**Comment by brentryanjohnson** [comment]
@mcharg It's trivial to adjust now that the glossary pattern is applied (if it builds!). I think what we have sums it up pretty well, from what we know so far. As long as it's not inaccurate, we can adjust the details over time.

**Pull request merged**
