### PR TITLE
Dev-->master for LWCF status update

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:evergreen_tree: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/how-it-works/land-and-water-conservation-fund/)

Changes proposed in this pull request:

- Updates status of Land and Water Conservation Fund
- Adds design pattern to flag update date

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@jennmalcolm We have to increment the release version in two places during the Jekyll --> Gatsby transition. I haven't done so, yet.

The two locations are:
- [`_config.yml`](https://github.com/ONRR/doi-extractives-data/blob/dev/_config.yml)
- [`gatsby-config.js`](https://github.com/ONRR/doi-extractives-data/blob/dev/gatsby-site/gatsby-config.js)

**Comment by brentryanjohnson** [comment]
I'll go ahead and push the version increments to `dev`.

**Comment by jennmalcolm** [comment]
Ok, @brentryanjohnson you're too fast for me to keep up with today.

**Comment by brentryanjohnson** [comment]
No worries, @jennmalcolm. I already had the files open. :)

**Pull request merged**
