### PR TITLE
3835 filterable table

### LINKED ISSUE #3835: Build MVP revenue filterable table
I pulled out the charts from the design and also created a version without the sparklines, since I think those could be added after the MVP.  I also made it color and not sketchy again in this version, so Jeff knows what the desired colors are.

With Sparklines:
https://t81vx1.axshare.com/#g=1&p=revenue_table_-_alt

Without Sparklines:
https://t81vx1.axshare.com/#g=1&p=revenue_table_-_no_sparkline

### PR DESCRIPTION
**Pull request by master12**
Fixes #3835 #3850 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3835-filterable-table/)

Changes proposed in this pull request:

-  Added filterable table for Revenue Fiscal year
- Added link on home page
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The downloads link on the filterable table page should go here: https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3835-filterable-table/downloads/#revenue

**Comment by mcharg** [comment]
I'm just waiting on the updated download link before approving.

**Comment by mentastc** [comment]
When filtered by State totals shows up

image

**Comment by mentastc** [comment]
when filtered by land owner the Federal total is under represented and doesn't display the revenues that are in the land category of "not tied to lease" for 2018 that equals $2,831,594.12

image

**Comment by jennmalcolm** [comment]
@mentastc I opened #3928 for that issue.

**Pull request merged**
