### PR TITLE
Homepage copy edits

### LINKED ISSUE #4186: Finalize words on new homepage
Design: https://sjzq35.axshare.com/#g=1&p=alt_tab_styling

Text to finalize:
- [x] Intro copy
- [x] Revenue tab intro copy
- [x] Revenue table link
- [x] Explore revenue links (explore, filterable table, revenue by company, how it works, downloads)
- [ ] Accounting year label
- [x] Disbursements intro copy
- [x] Explore disbursements links (explore, how it works, downloads)
- [x] Disbursements trends copy
- [x] Production tab intro copy
- [x] Explore production links (explore federal, Native American, how it works, downloads)
- [x] Data by state intro copy
- [ ] Map legend

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #4186

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/homepage-copy/beta/)

Changes proposed in this pull request:

- Edits intro copy, micro copy, and link text
- Normalizes subheading styling

### CODE REVIEW

**Comment by mcharg** [comment]
@brentryanjohnson We need these changes on the new homepage (Mojo's branch) not the old one.

**Comment by brentryanjohnson** [comment]
Thank you, @mcharg.

This branch is sliced from @mojobnichols's, and the destination for merging is his branch.

brentryanjohnson wants to merge 5 commits into 4174-BuildNewHomepage from homepage-copy

I branched off his to review the copy independently of his other work, and then it can be merged into what he's working on when the copy is agreed upon.

**Comment by mcharg** [comment]
"Revenue in detail" didn't convey to users what the filterable table does.  "Filter revenue data" worked slightly better in testing, but there may be a better alternative we haven't tried yet.  When we asked for suggestions after they saw what was behind the link, users suggested things like "Revenue by commodity", "Find a specific mineral number" or "Reach a specific state or commodity".


Otherwise, the edits look good.

**Comment by brentryanjohnson** [comment]
This copy retains "Filter revenue data" for the top link (by the subheading), and changes the bottom link to "Revenue in detail," so the wording is consistent with the other links. The two revenue table links are tied together with the new icon, the hope being that it's evident they go to the same place, with one link wording phrased as a call to action, while the other is phrased as a noun destination.

I'll consider alternatives.

**Comment by mcharg** [comment]
It did have the chart icon when we had the "Revenue in detail" link in testing, so the table icon might help with understanding.

**Comment by brentryanjohnson** [comment]
Yes, I wonder if we can test the link text again, since we've changed everything around the links. It might change heuristics with everything shifted around.

**Comment by mcharg** [comment]
Sounds like a plan.

**Pull request merged**
