### PR TITLE
Adds database blog post

### LINKED ISSUE #3963: Write blog post about database, Hasura, Apollo, GraphQL
@master12 is doing some cool and interesting things with graphql for the revenue table queries. We should blog about it.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3963

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/blog-post-database/blog)

Changes proposed in this pull request:

**Dated for next sprint publication**

### CODE REVIEW

**Comment by mojobnichols** [comment]
Preview doesn't work

**Comment by brentryanjohnson** [comment]
Yep, @mojobnichols. Looks benign:

> Whoops, our S3 keys were rotated during your build and became out of date. This was not a problem with your site build, but if you restart the failed build it should work on the next try. Sorry for the inconvenience!

**Comment by brentryanjohnson** [comment]
Should be ready to review @mojobnichols and @jennmalcolm

**Comment by brentryanjohnson** [comment]
We're putting this in WIP status pending (1) the accessibility blog post and (2) testing on cloud.gov.

**Comment by jennmalcolm** [comment]
@brentryanjohnson @mojobnichols should we publish this with our next release?

**Comment by mojobnichols** [comment]
It looks good.

**Pull request merged**
