### PR TITLE
Adds shaping blog post

### LINKED ISSUE #5042: blog post on shaping and new site

### PR DESCRIPTION
**Pull request by mcharg**
Fixes #5042 

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/shaping-blog/blog)

Changes proposed in this pull request:

- Adds shaping blog post

### CODE REVIEW

**Comment by mcharg** [comment]
@jennmalcolm Can you see if you can figure out why the image of the beta site isn't showing up?  It's similar to what happens on some of the older blog posts, but I can't figure out why.

**Comment by jennmalcolm** [comment]
Yes, I'll look at it @mcharg.

**Comment by mcharg** [comment]
@jennmalcolm Can you also see if you can get the Basecamp links to work?  I copied directly from the remote design studio post and it's working there, but not in this one.

**Comment by jennmalcolm** [comment]
Yes @mcharg, I am working on it now.

**Comment by jennmalcolm** [comment]
I couldn't get the last image to work, so I just removed it. I will add @lpgoldstein and @Maroyafaied for one last review (check links, etc.) before merging.

**Comment by Maroyafaied** [comment]
@jennmalcolm @mcharg there's blank space where that image I think is supposed to be removed. 
image

**Comment by jennmalcolm** [comment]
Oh no @Maroyafaied that image was working before. It looks like a new one is broken now that I removed the last one. Very weird. Maybe @master12 can take a look tomorrow to see if he can fix it.

**Comment by mcharg** [comment]
All the images are working for me now.  @Maroyafaied @lpgoldstein Can you check, as well?

**Pull request merged**
