### PR TITLE
Monthly Revenue and Production July 2019 (take 2)

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/monthly_revenue_production_july_2019_2/)

Changes proposed in this pull request:

- updates homepage charts and revenue trends
- updates downloads (rev and production monthly)
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@maroyafaied, could you check the revenue trend numbers, and I will check the graph numbers?

**Comment by Maroyafaied** [comment]
@jennmalcolm I already checked the graph numbers. I can do the trends as well now

**Comment by Maroyafaied** [comment]
@jennmalcolm trends numbers are correct 
image

**Comment by master12** [comment]
Creating new PR since this PR is not getting the new commits

**Pull request closed without merging**
