### PR TITLE
3623 downloads revenue

### LINKED ISSUE #3623: Build Revenue Downloads Page in Gatsby
https://revenuedata.doi.gov/downloads/federal-revenue-by-location/

### PR DESCRIPTION
**Pull request by master12**
Fixes #3623

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3623-downloads-revenue/downloads/federal-revenue-by-location/)

Changes proposed in this pull request:

- Added all 3 revenue pages
-
-

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
At least one markdown link isn't being compiled:

> We also have [notes on this data](https://github.com/onrr/doi-extractives-data/wiki/Data-Catalog#federal-revenue) from the web development team as they built the interactions on this site.

I suspect this is due to a hack from the old site. Since the page mixes markdown and HTML, the past team created a `markdown` boolean attribute to tell it to compile the markdown as markdown:

```
<p class="u-margin-top" markdown="1">We also have [notes on this data](https://github.com/onrr/doi-extractives-data/wiki/Data-Catalog#federal-revenue) from the web development team as they built the interactions on this site.</p>
```

Since we don't appear to have the same custom attribute in Gatsby, how would you like to handle this, @master12?

**Comment by master12** [comment]
@brentryanjohnson Not sure what issue you are seeing? The link works for me?

**Comment by brentryanjohnson** [comment]
This link, @master12:

uncompiled markdown link

**Comment by master12** [comment]
@brentryanjohnson Aaaa I see. They did it differently on the company page. Bottom line don't mix markdown and html in the same element. That is just weird. You can use html and markdown in the same file. So this issue can be resolved by simply using html or markdown but not both in the same element. That is a terrible, awful hack and it should not be repeated ever in the history of the world. I suspect another junior level developer. I will fix it to match the other markdown file.

**Comment by brentryanjohnson** [comment]
@mentastc and I are going to update the monthly files and download pages and commit to this branch (and monthly production).

**Comment by brentryanjohnson** [comment]
FYI...the monthly link won't work in the preview, because the file is in a different branch and PR.

**Comment by jennmalcolm** [comment]
The file names in this subheading under scope on the revenue by location and revenue by company tabs are showing up with underscores instead of italicized like on the live site.

image

**Comment by master12** [comment]
@jennmalcolm ha! I mixed markdown with html. ok fixed.

**Comment by jennmalcolm** [comment]
@master12 you fixed it on the revenue by year tab, but it's still on the revenue by company tab.

**Pull request merged**
