### PR TITLE
Dev->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Adds query tool
- Updates state page intro content to align with product vision
- Adds product champion blog
- Updates monthly revenue data through October 2019 and production data through July 2020
- Fixes accessibility issues
- Updates production download page content
- Updates audit and assurances content
- Other minor updates and fixes

Data to check
Production Monthly (monthly_production)	
- [x] Homepage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Hompage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Data query tool	
- [x] Revenue
- [x] Production
- [x] Disbursements

### CODE REVIEW

**Comment by mcharg** [comment]
@brentryanjohnson Did you not merge the PR to add CY and FY to the years on the state pages?  I thought you did, but I'm not seeing that change in this.

**Comment by jennmalcolm** [comment]
@mcharg i did merge it but maybe it didn’t build. I’ll go into Federalist and see if that’s the problem.

**Comment by jennmalcolm** [comment]
@mcharg. It doesn’t seem like there’s any problem with that build, and I’m seeing calendar year and fiscal year on the state pages in dev. Maybe you just need to refresh?

**Comment by mcharg** [comment]
@jennmalcolm You know what, I was looking for FY and CY right before the year and was blind to it as a glossary... sigh.

**Pull request merged**
