### PR TITLE
Updates revenue rates table in how it works

### LINKED ISSUE #3785: Update revenue rates
Related to #3679 

- Update [revenue rates in how it works](https://revenuedata.doi.gov/how-it-works/revenues/) in accordance with @Maroyafaied's findings.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3785

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/revenue-rates-table/how-it-works/revenues/)

Changes proposed in this pull request:

- Updates bonus, rent, fee, and royalty rates in revenue table

### CODE REVIEW

**Comment by Maroyafaied** [comment]
Looks good, my only suggestion is to remove the wording under the bonus for oil and gas onshore to be consistent with other commodities. Also for rent for solar and wind onshore, I would change the wording to "determined by number of acres times the annual per acre zone rate" 
image
image

**Comment by brentryanjohnson** [comment]
Okay, @Maroyafaied, once this builds, could you give it another look?

**Comment by Maroyafaied** [comment]
Yes, I will.

**Comment by Maroyafaied** [comment]
It look great @brentryanjohnson

**Comment by master12** [comment]
@Maroyafaied good i already merged it. I will delete the branch then

**Pull request merged**
