### PR TITLE
Rev updated 19

### PR DESCRIPTION
**Pull request by jennmalcolm**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/Rev-updated-19/)

Changes proposed in this pull request:

- updates revenue monthly and annual through FY 2019
- updates release date to tomorrow

Revenue Fiscal Year (fiscal_year_revenue)	
- [x] Homepage: FY bar charts
- [x] How it works: Native American revenue table 
- [x] Explore data: Filterable revenue data table 
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Hompage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by lpgoldstein** [comment]
The How it works Native American Revenue table is rounding down 
image

image

**Comment by lpgoldstein** [comment]
Fiscal year Download: xls and csv files updated with correct dates and file size 
image
image

**Comment by lpgoldstein** [comment]
monthly  Download: xls and csv files updated with correct dates and file size
image
image

**Comment by lpgoldstein** [comment]
Hompage: monthly bar charts look good 
image

**Comment by lpgoldstein** [comment]
monthly revenue trends look good as well. 
image

**Comment by jennmalcolm** [comment]
I reviewed the filterable revenue table so I will merge now so that we don't have a memory hanup trying to merge everything at once later @mentastc please do a thorough review of the numbers in dev.

**Pull request merged**
