### PR TITLE
Audit cleanup

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[✔️ PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/audit-cleanup/)

Changes proposed in this pull request:

- Multiple capitalization and punctuation edits based on our [content style guide](https://github.com/ONRR/doi-extractives-data/wiki/Content-style-guide)
- Correct proportions of blog author images to clear audit flags for best practices
- Move state revenue streams PDFs to fix broken links
- Remove rogue spaces between sentences
- Fix broken links on multiple pages
- Fix taxonomy on multiple how-it-works pages
- Remove manually curated and automatically injected production and revenue data from how-it-works Native American pages
  - Adds links to query data on how-it-works Native American pages
- Adds meta descriptions to all pages to clear SEO audit flags

### CODE REVIEW

**Comment by mcharg** [comment]
@brentryanjohnson Are you going to list out the fixes, so we know what to review?

**Comment by brentryanjohnson** [comment]
Sure, @mcharg. I'm still finishing up the audit, so it's still in WIP status. In the meantime, [the diff](https://github.com/ONRR/doi-extractives-data/pull/4877/files) shows all the changes.

**Comment by brentryanjohnson** [comment]
☝️ Fixes #4863

**Comment by brentryanjohnson** [comment]
I've merged `dev` into this branch and pulled the WIP status. This should be ready to review, @jennmalcolm and @mcharg.

**Comment by mcharg** [comment]
@brentryanjohnson If you pull in the branch in #3924, we can test linking to the query tool with Native American selected as the land category.

**Comment by jennmalcolm** [comment]
I know this page will be going away, but for now, should we change the  "Explore data" to title case too since it is an h1?
image

**Comment by brentryanjohnson** [comment]
Good catch, @jennmalcolm. ☝️ Should be fixed with this commit.

**Pull request merged**
