### PR TITLE
Fix prod charts sync

### LINKED ISSUE #3392: Fix remaining homepage bugs
Fix the issues that weren't show stoppers for the release.

On hover, the swatches in the table should change to the hover color.

- [x] Fixed

- [x] Tested

Table header for the month should have the year after the month name. (e.g. Mar 2018)

- [x] Fixed

- [x] Tested

Production charts aren't moving together on click.
- [x] Fixed

- [x] Tested

Could use a bit more space between the primary nav and tabs.
- [x] Fixed

- [x] Tested

Period drop-down is misaligned and missing the arrow on IE.  It does at least work, so users can get to the content, so I'm not putting this in show stoppers.
image
image

- [x] Fixed

- [x] Tested

### PR DESCRIPTION
**Pull request by master12**
Fixes #3392 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/fix-prod-charts-sync/)

Changes proposed in this pull request:

- Created single reducer
- Added set data selected
- refactored code

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 

Works great on:
- Chrome
- Firefox
- IE
- Edge

Doesn't work so great on:
- iPhone Safari
- iPad Safari

When I click on a bar, the last selected year or month stays selected.  The new bar gets selected and the table updates, but the other charts aren't affected.
iPhone Yearly
img_9735
iPhone Monthly
img_9736
iPad
img_1039

**Comment by mcharg** [comment]
@jennmalcolm Are you okay with leaving the behavior as is on Safari?  See my comment above about the issue.

**Comment by master12** [comment]
The click event is not firing. Will try to change to onMouseDown since hover is working

**Comment by jennmalcolm** [comment]
@mcharg I approved before I saw your comment and had not looked on my phone. I too would like that issue to be fixed before merging.

**Comment by master12** [comment]
Ok mousedown works. I noticed another issue so will fix that and update.

**Comment by master12** [comment]
@mcharg I noticed if you move your mouse really fast the hover event doesnt fire enough to keep up. Which results in the legend still thinking something is hovered. Not sure how if can fix that due to it being a  browser speed issue. DO you still want to keep the hover feature updating the legend?

What I did add was an mouseout on the entire chart and that helps to catch it only if your mouse leaves the chart area. So its still an issue but thats the best I can do.

**Comment by mcharg** [comment]
Yes, I think we should keep it to be consistent with the Explore Data charts.  Most users probably won't mouse really fast and if they end up in a weird state, it's easy enough for them to fix it by hovering over something else or refreshing the page.

**Comment by master12** [comment]
@mcharg I think I got it fixed for the hover. Added a background rect to catch hover events and clear the hover.

**Comment by jennmalcolm** [comment]
Looked at it on my iphone, and it seems like we still have the issue of the 2017 bar saying highlighted. Also, the bars for all commodities are not synced yet on my phone.

**Comment by mcharg** [comment]
I'm still seeing the issue on my phone, as well.

**Comment by master12** [comment]
@mcharg @jennmalcolm Could you try one more time? I cant recreate the issue any more on my macbook even with the emulator set to iphone se and ios

**Comment by mcharg** [comment]
@master12 I'm still seeing it on both my phone and iPad.  Could it be something with an OnTap event?

**Comment by mcharg** [comment]
And I confirmed that it's working fine on my Android phone.

**Comment by master12** [comment]
Ok I dusted off my ipad and it does work but very poorly. 
1. Really hard to get your finger to hit the bar. 
2. For some reason I hit it once its highlighted and the hit it again to actually select it. 

But it did work but it was a bad experience. Please try again and see if you can get it to work even if it's terrible. 

My thought on a solution is to have a overlay that is wider then the current max. Basically it will be the calculated max width vs the 15 px that is currently set. I will also try to not make it highlight on first touch. weird...

My thought though is not to hold up this fix for that.

**Comment by jennmalcolm** [comment]
It's working now on my phone. It is still a little hard to select a year, but not too bad. I'll merge this in .

**Comment by mcharg** [comment]
It's working on my phone, too!

**Pull request merged**
