### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by lpgoldstein**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Added calendar year revenue data for 2019 
- Added disbursements data for December 2019 
- Added blog post about being tool agnostic 
- Updated Geothermal labels and units 
- Added "long ton" to glossary
- Updated coal excise tax rates

Revenue Calendar Year (calendar_year_revenue)	
- [x] Explore data: Revenue detail by phase 
- [x] Explore data: bar charts revenue trends by resource 
- [x] State pages: revenue detail by phase 
- [x] State pages: commodities bar charts and by county maps & table 
- [x] Offshore pages: commodities bar charts and by offshore area map & table 
- [x] Download: xls and csv files updated with correct dates and file size

Disbursements Monthly (monthly_disbursements) 	
- [x] Homepage: disbursements trends
- [x] Download: xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@lpgoldstein I can't add you as a reviewer since you set up this PR, but could you also take a look at dev and help check data if needed?

**Comment by mcharg** [comment]
Where should I be looking for the geothermal updates?  It's still showing sulfur as the unit in the query tool and bar charts.
image
image

**Comment by mentastc** [comment]
For now it was just changed in the content on the downloads page. DORC needs to update the data sets but we haven't heard back from them yet.

**Comment by mentastc** [comment]
In the revenue chart the inspection fees, civil penalties, and other revenue in the parenthesis didn't update.

image

**Comment by lpgoldstein** [comment]
@jennmalcolm This is ready to go!

**Pull request merged**
