### PR TITLE
Fixed rounding issue in function src/js/utils.js formatToSigFig_Dollar

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes # 4442

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4442-RoundingError/)

Changes proposed in this pull request:

rounding in revenue trends and other places(?) works correctly
-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols You probably want @mentastc or @lpgoldstein to review this to make sure the numbers are rounding to match the data.

**Comment by brentryanjohnson** [comment]
@mojobnichols Will you explain the reason for the `package.lock` changes for PR reviewers?

**Comment by jennmalcolm** [comment]
The rounding on the revenue and disbursements trends is correct now. @mojobnichols, do you know if this change could have impacted anything else on the site? I took a look at the dotted lines on the explore data graphs because I remember Jeff saying that the rounding related to those, and they appear fine. 

I did notice while I was reviewing this PR that the disbursements trends is including the US TreasuryAI line in US Treasury. I know it's confusing, but that should be in the Native American number (AI stands for American Indian), so I opened #4614 for that.

**Comment by mentastc** [comment]
Karen O, just stopped by asking about US Treasury AI and I looked it up again, here's what Maria said about it "is the American Indian portion - South Half of the Red River Settlement, and the Mescal Settlement."

**Pull request merged**
