### PR TITLE
Updates CY Revenue file

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/cy_revenue/)

Changes proposed in this pull request:

-Updates CY revenue file for CSV and xlsx
-Updates download text

Revenue Calendar Year (calendar_year_revenue)	
- [x] Explore data: Revenue detail by phase 
- [x] Explore data: bar charts revenue trends by resource 
- [x] State pages: revenue detail by phase 
- [x] State pages: commodities bar charts and by county maps & table 
- [x] Offshore pages: commodities bar charts and by offshore area map & table 
- [x] Download: xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by jennmalcolm** [comment]
I added you as a reviewer, @Maroyafaied, since there are quite a few places on the site to check the data, so you and @lpgoldstein can split it up.

**Comment by Maroyafaied** [comment]
@mentastc it should say 2019
image

**Comment by mentastc** [comment]
Thanks! I missed that one, I'll make the edit.

**Comment by Maroyafaied** [comment]
on the homepage bar charts, it's a few dollars off for the federal onshore revenue which makes the total also a few dollars off. Not sure if it's a rounding thing.

image

image

**Comment by Maroyafaied** [comment]
@lpgoldstein I checked off on the checklist what I have reviewed, I also reviewed the homepage bar charts which was not on the checklist.

**Comment by mentastc** [comment]
@Maroyafaied I fixed that intro sentence.

**Comment by lpgoldstein** [comment]
Looks good!

**Pull request merged**
