### PR TITLE
Adds FY revenue download file for 2018

### LINKED ISSUE #3478: Update annual revenue for FY2018
Update annual revenue for FY2018

- [x] Check file to ensure it adheres to the new file format

- [x] Check file to ensure there are no obvious data issues

- [x] Update Data Download

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3478

[:dollar: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/update-annual-revenue/downloads/federal-revenue-by-location/)

Changes proposed in this pull request:

- Adds FY revenue file for download, fiscal years 2006–2018
- Edits intro copy to clarify the consolidation of FY revenue data into one file instead of three

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@brentryanjohnson I get 404 error when I click the preview button

**Comment by brentryanjohnson** [comment]
It probably hadn't finished building yet, @Maroyafaied. Try again, and let me know if it works. 👍

**Comment by brentryanjohnson** [comment]
It looks like Data Retrieval needs to look at a field in the file and confirm. Let's hold on merging.

**Comment by mentastc** [comment]
@brentryanjohnson  Here is the updated file from DR that needs to replace the original. 
[FY18 Federal Revenues.xlsx](https://github.com/ONRR/doi-extractives-data/files/2691911/FY18.Federal.Revenues.xlsx)

**Comment by brentryanjohnson** [comment]
The file should be ready to go @mentastc. Please review when you have time.

**Pull request merged**
