### PR TITLE
Data refactor, offshore pages, and much much more

### LINKED ISSUE #3620: Build Offshore Page in Gatsby
https://revenuedata.doi.gov/explore/offshore-alaska/

### PR DESCRIPTION
**Pull request by master12**
Fixes #3620 #4122 #4004 #4164 #4121

[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/onrr/doi-extractives-data/3620-offshorepages/)

Changes proposed in this pull request:

- Added county maps for revenue on state pages
- Fixed Explore data page federal revenue by filtering native american
- Change county to parish or borough based on logic on county maps
- Refactored revenue and production data input
- Updated download pages for excel and csv downloads of production disbursements and revenue
- Offshore pages are no longer static
- Revenue for Native Americans in how it works pages are no longer static

### CODE REVIEW

**Comment by mentastc** [comment]
@master12  the generated intro paragraph isn't fully populating. Its not saying what commodity it leads the nation in, also I believe the statement goes away if it doesn't lead in any commodity. 

image

**Comment by Maroyafaied** [comment]
@master12 I get an error message when trying to download fiscal year revenue 
image
image

**Comment by Maroyafaied** [comment]
@ I get the same error message for revenue by calendar year csv, fiscal year revenue xls, revenue by company xls and csv, disbursement by month xls and csv, disbursement by year xls and csv

**Comment by Maroyafaied** [comment]
@master12 total revenue in 2018 is not matching the numbers in the excel sheet 
image
image

**Comment by mentastc** [comment]
- On the explore data national page, all the revenues appear to add up but oil shale isn't visible (I thin't its added into the oil and gas total though. Not sure if that should be fixed or not.

- The all commodities revenue looks to be off, It looks like its not including the items that don't have a commodity like civil penalties and inspection fees. This also looks to be the reason why Maroya shows total revenue to be under reported. 
image

image

**Comment by master12** [comment]
@mentastc @Maroyafaied So i was filtering out the Not tied to a commodity due to the fact it would show up in the chart section. So I just dont show it in the chart section.

**Comment by master12** [comment]
@mentastc @Maroyafaied For the downloads, I think I will need some help creatign the files that are needed for some of these. I fixed the links for the files I have for production, revenue and disbursements. But for native american and by company I think I need help on those, also need to figure out the best location to put those since I dont want to read those into my Graphql builds. So let me know when some one has some time to work through this. Thanks

**Comment by Maroyafaied** [comment]
@master12 The numbers are not matching for me with and without Not tied to a lease 
image
image
image

**Comment by Maroyafaied** [comment]
@master12 Never mind, the numbers match, I didn't take out Native American before. 
image

**Comment by jennmalcolm** [comment]
@mentastc could you make sure @master12 has all of the files for the downloads?

**Comment by mentastc** [comment]
@master12  I think you have all the files you should need. The revenue by company file isn't changing from the one thats currently online. We can delete the Native American Revenue download page, that revenue is now captured in what was previously the Federal revenue file (Ryan and I can do this, as there is an issue #4126 out there to make this change) You should have The Federal CY and FY production file in you email from earlier this week. Let me know if I'm missing a file that you need.

**Comment by mentastc** [comment]
State Revenue maps that have county revenue are generating in a random order, they should either be alphabetical or by revenue amount.  Amounts displayed are correct. 
image

**Comment by mentastc** [comment]
@master12 Oil Shale doesn't appear in the revenue mega chart on the national page and state pages, I believe this is because Oil shale is a commodity that didn't exist until three years ago in our data. @jennmalcolm  is this an issue that should be fixed now? It's a current issue on the site. 
image
image

**Comment by mentastc** [comment]
@master12  not all products are showing on the National explore data page for production, I count 24 products but it should be displaying 36, for instance.

Here are the products I think should show up:

Borate Products   (tons)
Brine Products (tons)
Clay (tons)
Coal (tons)
Copper Concentrate (tons)
Ferro Phosphorous Slag (tons)
Gas (mcf)
Geothermal - Direct Use, Millions of   Gallons
Geothermal - Direct Utilization, Hundreds   of Gallons
Geothermal - Direct Utilization, Millions   of BTUs
Geothermal - Electrical Generation,   Kilowatt Hours
Geothermal - Electrical Generation, Other
Geothermal - Electrical Generation,   Thousands of Pounds
Geothermal - sulfur
Gilsonite (tons)
Gold and Silver (tons)
Gold and Silver Products (oz)
Hardrock Products (tons)
Langbeinite (tons)
Lead Concentrate (tons)
Muriate Of Potash-Granular (tons)
Muriate Of Potash-Standard (tons)
Oil (bbl)
Other Coal Products (tons)
Phosphate Raw Ore (tons)
Potash (tons)
Potassium Products (tons)
Purge Liquor (tons - equivalent)
Quartz Crystal (tickets/pounds)
Salt (tons)
Soda Ash (tons)
Sodium Bi-Carbonate (tons)
Sodium Products (tons)
Sodium Sesquicarbonate (tons)
Trona Ore (tons)
Zinc Concentrate (tons)

**Comment by mentastc** [comment]
@master12 old monthly revenue files are being used to generate the homepage graphs, for instance CY 2018 offshore revenue is off. please use the files that are currently on the site for the graphs and also replace the monthly revenue download, it only goes to April and we have up to June. 
image

**Comment by lpgoldstein** [comment]
Fiscal year production charts are missing Native American production, but monthly and calendar year appears okay. 

image

**Comment by lpgoldstein** [comment]
@master12 the preview link isn't loading

**Comment by master12** [comment]
Everything is working now

**Comment by master12** [comment]
@lpgoldstein Our fiscal year production file has no native american listed. Do you know why? The file its using is in the downloads/production

**Comment by lpgoldstein** [comment]
@master12 The live site has the FY Native American production - I'm not sure which file it is pulling. How can I figure that out?

**Comment by Maroyafaied** [comment]
@master12 , The Native American revenue paragraph should be taken out in the download data & documentation page along with the Native American revenue download page since this data is now included in the Revenue by year download page. Also, we need to edit the paragraph under revenue by year to say that it does include Native American revenue. 
image
image
image

**Comment by jennmalcolm** [comment]
@Maroyafaied, @brentryanjohnson will be handling the revenue downloads page consolidation in #4406 so that doesn't need to be done as part of this PR.

**Comment by master12** [comment]
@jennmalcolm All changes have been made and updated prod files have been merged please feel free to merge this to dev once the new build finishes

**Comment by jennmalcolm** [comment]
Ok thanks @master12.

@lpgoldstein and @Maroyafaied could you do a final data review, and I will do my review tomorrow morning, with the goal of merging early tomorrow and releasing by Wednesday. Please check off these elements of the data once you have verified they are correct:

- [ ] Explore data page production
- [ ] Explore data page revenue - megachart and product graphs
- [ ] State/offshore page production
- [ ] State/offshore page revenue
- [ ] Homepage graphs - revenue and production
- [ ] Revenue trends 
- [ ] Native American production
- [ ] Native American revenue
- [ ] Production and revenue downloads - FY and CY

You can add to this list if I have forgotten anything. Thanks.

**Comment by lpgoldstein** [comment]
@Maroyafaied I spot checked the production data and it looks like oil is off - could you please take a look as well? I used the CY download file from the link in the preview. 
image

**Comment by lpgoldstein** [comment]
I'm getting a 404 for Revenue by Company Downloads  -otherwise production and revenue downloads look good. 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/onrr/doi-extractives-data/3620-offshorepages/downloads/federal_revenue_by_company_CY2013-CY2018.xlsx

**Comment by lpgoldstein** [comment]
Revenue chart on homepage only goes through April but we have through June on the live site. Numbers look correct though. 
image

**Comment by lpgoldstein** [comment]
homepage production charts look good.

**Comment by Maroyafaied** [comment]
explore data revenue megachart and product graphs look good.  I will be checking state/offshore revenue and production now.

**Comment by Maroyafaied** [comment]
For the state production, for geothermal (ex:Nevada) the electrical generation and the direct utilization is listed as the same number
image
image

**Comment by Maroyafaied** [comment]
on the offshore pages, the year in the revenue paragraph needs to be corrected to 2018
image

**Comment by Maroyafaied** [comment]
Need to add space in the federal revenue paragraph in the state pages
image

**Comment by Maroyafaied** [comment]
The revenue by month file only goes till April 2019 (should be June 2019), so the revenue trends say April 2019 and the homepage revenue monthly charts only show till April 2019 
image

**Comment by Maroyafaied** [comment]
No data shows up in the home page charts for Native American disbursements 
image

**Pull request merged**
