### PR TITLE
Fixed meta description for Blog list

### LINKED ISSUE #4767: Fix meta description for blog-list
Our index page, which lists blog posts, isn't pulling in our `meta` description for SEO purposes.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #4767

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4767-FixMetaDescriptionBlogList)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@jlouis-onrr This keeps flagging as a broken build. Do you mind having a look when you get a chance?

**Comment by jlouis-onrr** [comment]
For sure, I will check this out to see what causing the build failures.

**Comment by jlouis-onrr** [comment]
@brentryanjohnson Im able to successfully build the branch locally.  However, when I try to view the details of the errors via federalist I'm not able to see them due to permissions.

"Unauthorized Apologies; you don't have access to Federalist! Please contact the Federalist team if this is in error."

Is this something I can get access to for further review?

**Comment by brentryanjohnson** [comment]
You should be good to go now, @jlouis-onrr, thanks to @amirbey.

**Comment by jlouis-onrr** [comment]
@brentryanjohnson Thanks for getting me setup as Federalist user.  I was able to successfully build the branch on federalist.

[Federalist Builds](https://federalistapp.18f.gov/sites/472/builds)

**Comment by brentryanjohnson** [comment]
@jlouis-onrr and I have concerns about the build status of this one. The PR status isn't updating with Federalist. We're not sure why that is, but this PR is only one line of code, so we're going to close this PR and open a new one.

**Pull request closed without merging**
