### PR TITLE
Add beyond open data blog post

### LINKED ISSUE #3828: Publish blog post on NRRD alignment with IDEA and OPEN Data acts
Publish blog post written last sprint on how NRRD aligns with IDEA and OPEN Data acts#3788

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #3828

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/open-data-blog-post/blog/beyond-open-data)

Changes proposed in this pull request:

- New blog post on NRRD open data

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Sorry I didn't see this before, but this really should be "laws" or "statutes" rather than "regulations."  I could make the change if you want @lpgoldstein. 

image

**Comment by jennmalcolm** [comment]
I can update the date when I prepare the release.

**Comment by brentryanjohnson** [comment]
I would suggest one more edit, @lpgoldstein. Under 21st Century IDEA, there is a line "Here are some of the requirements of the 21st Century IDEA...". All of the subheadings are indeed requirements of the act, but one of them is "Duplication." Since the act requires the _elimination_ of duplication, we should probably word it that way. As it appears now, upon skimming, it looks like duplication is a requirement of the act.

Other than that, it looks good!

**Comment by brentryanjohnson** [comment]
☝️ This commit includes the suggested subheading edit, @lpgoldstein.

**Pull request merged**
