### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes made in this release:
- Added blog article about building team technical capacity
- Refactored paths for archive assets
- Added skip to to main anchor and tabindex on homepage
- Other accessibility improvements
- Updated disbursements download page
- Corrected bug that omitted inspection fee data on revenue table
- Updated monthly disbursements and revenue downloads pages
- Improved rounding 
- Refactored data query structure disbursements

Based on the data files changed, we need to check the data in these features (@Maroyafaied and @mentastc, please check the data):

Disbursements Monthly (monthly_disbursements)
- [x] Homepage: disbursements trends
- [x]  Download: xls and csv files updated with correct dates and file size

Production Fiscal Year (fiscal_year_production)
- [x] Homepage: FY bar charts
- [x]  Download: xls and csv files updated with correct dates and file size

Other data to check due to bug fix
- [x] Inspection fee data on revenue table

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@jennmalcolm the disbursement monthly files are not showing the August data.

**Comment by Maroyafaied** [comment]
Everything looks good for Revenue Monthly. But not seeing August data for disbursements. 
- [X] Homepage: revenue trends charts
- [X] Hompage: monthly bar charts
- [X] Download: xls and csv files updated with correct dates and file size

**Comment by jennmalcolm** [comment]
@Maroyafaied I merged the PR with the disbursements data, but it doesn't look like it built the preview, so I'm tryin again.

**Comment by jennmalcolm** [comment]
@Maroyafaied the preview link works now for the disbursements.

**Comment by Maroyafaied** [comment]
@jennmalcolm Disbursement looks good

**Pull request merged**
