### PR TITLE
added noneenrgy minerals to gatsby

### LINKED ISSUE #3545: Build Nonenergy Minerals page in Gatsby
https://revenuedata.doi.gov/how-it-works/nonenergy-minerals/

### PR DESCRIPTION
**Pull request by master12**
Fixes #3545 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3545-howitworks-nonenergy-minerals/how-it-works/nonenergy-minerals/)

Changes proposed in this pull request:

- Added non-energy minerals to gatsby build
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The links within our site are all returning 404 pages. Will that resolve in dev or is that the redirect issue?

**Comment by mcharg** [comment]
@master12 With the menu, there's a gap between about 768 and 480 px where the right nav moves to the bottom of the page and the table of contents isn't there.  Can we use the table of contents menu whenever the right nav isn't there rather than moving it to the bottom?

**Comment by master12** [comment]
@mcharg Ugh links... They will work in prod. There is no simple solution to work around this issue in preview mode. I would prefer to let it go since we are so close to getting everything transitioned and this issue wil disappear in preview mode once we dont have the hybrid gatsby/jekyll world.

I will look at a menu solution. thanks for catching that.

**Comment by master12** [comment]
@mcharg The menu issue will be fixed in my next PR. If there are no more issues other than the link and the menu please approve the pr. Thanks

**Pull request merged**
