### PR TITLE
Dev-->master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)
[Pattern Library Preview](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/patterns)

Changes proposed in this pull request:

- New disbursement feature
- Gatsby explore data and about pages
- Archive pattern for content that will not be updated
- AML, LWCF, and HPF content updates
- Smooth scrolling
- Pattern library component additions
- Other minor content updates

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@brentryanjohnson or @master12 I don't know what's going on with the pattern library preview. Do I have the wrong URL, or is there something wrong?

**Comment by mcharg** [comment]
Do we only have Funded by Congress numbers for 2017?

**Comment by mcharg** [comment]
Also, the glossaries on Explore Data aren't showing definitions.

**Comment by brentryanjohnson** [comment]
@mcharg Good question about the Economic Impact section and the archive flag. I haven't flagged it as archive because, while it was created during the USEITI era, I don't believe it was specific to USEITI in the same way that the flagged content is. For instance, Reconciliation was part of compliance reporting to meet the EITI standard, but my understanding is that including the Economic Impact data was a discretionary choice by the multi-stakeholder group. 

It's a great question and one I'll continue to consider.

**Comment by master12** [comment]
Comments for release:
1. Performance on IE 11:  Nothing can be done about this currently. It takes 28 secs for react and 30s for "state-pages-min" to run. In Prod there is no react so it takes 30 secs. Not sure why IE 11 takes so long to let the code write to the DOM. The best thing we could do is provide a loading page icon as a quick fix. 
2. The map is not clickable in prod so this can be a seperate bug fix and should not impact this release.

All issues have been resolved other then the performance and the state map bug which exists in prod already.

**Comment by mcharg** [comment]
@master12 Is there a new preview link for this build?  None of the issues are fixed when I click on the Preview link.
- Accordions are still broken
- Glossaries are bringing up blank definitions
- Responsive behavior isn't there on the disbursements summary table
- You said you were going to talk with @brentryanjohnson about whether we have "funded by Congress" numbers for years prior to 2017

**Comment by master12** [comment]
Its still building. Please hold for another 5 mins

**Comment by master12** [comment]
Hold on. Found a production only error. Will let you know when this is fixed. The accordians should be fine but this is affecting the glossary

**Comment by brentryanjohnson** [comment]
@master12 Land and Water Conservation Fund values:

Year | Funded by Congress
-- | --
2014 | 306,043,000
2015 | 306,141,000
2016 | 450,000,000
2017 | 449,145,000

**Comment by brentryanjohnson** [comment]
I added to the release notes since this release was delayed, and we've since added content and features.

- Adds disbursement summary with past years' data
- Migrates portions of the codebase to GatsbyJS
- Adds GatsbyJS documentation
- Changes Federalist build config to accommodate GatsbyJS and build sequencing
- Adds archive call-out, metadata for USEITI content
- Adds 2017 national and state all production data and revises 2016 values (from EIA)
- Adds "8(g)" and "Authorization" to glossary and updates EITI Standard entry
- Corrects figures in summary history of Land and Water Conservation Fund (LWCF) appropriations
- Adds 2017 federal revenue by company data
- Improves layout of federal revenue by company data
- Corrects documentation regarding company revenue and revenue by location totals
- Updates Abandoned Mine Land (AML) content
- Adds "how it works" content for LWCF and Historic Preservation Fund (HPF) fiscal regimes and appropriations
- Adds actual Congressional appropriations to LWCF and HPF
- Adds smooth scrolling behavior as trial on production (allows user to track relative location of in-page links)
- Pattern library component additions

**Comment by mcharg** [comment]
In 767 Chrome, the chart bar is extending beyond the section width.

image

**Comment by mcharg** [comment]
And on my iPad - Safari.

**Comment by master12** [comment]
updated breakpoint should be good now

**Pull request merged**
