### PR TITLE
updated urls and redirects for downlaods

### LINKED ISSUE #135: Sizing problem on Sectors page subnav.
Width changes on scroll.

### PR DESCRIPTION
**Pull request by master12**
Fixes #135

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/135-downlods-page-urls-redirect/)

Changes proposed in this pull request:

- Changed links for downloads
- Also added redirects for old links to redirect to the new links
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@master12 this highlighted source file should link to the monthly disbursement rather than yearly. 
image

**Comment by Maroyafaied** [comment]
@master12 also these source files for revenue should be monthly 
image

**Comment by master12** [comment]
@Maroyafaied I updated the monthly links and monthly pages

**Comment by Maroyafaied** [comment]
@master12 the links for disbursement and revenue are still going to the yearly files.

**Comment by jennmalcolm** [comment]
From my review, I don't see any issues with the revenue links, but there are two with the disbursements. Could you fix these @master12 ? I've written what they're supposed to be. @Maroyafaied could you describe where you're seeing an issue with the revenue links? 
image

**Comment by Maroyafaied** [comment]
@jennmalcolm there is no longer an issue with the revenue links, they are good now.

**Comment by jennmalcolm** [comment]
@master12 one of the disbursements links is fixed, but this on is still going to the annual page when it should go to the monthly page. 
image

**Comment by Maroyafaied** [comment]
@jennmalcolm the revenue trends on the live site goes to the yearly download page, and on this branch it goes to monthly. 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied Monthly is right since they made the change to monthly source data for everything except the disbursements sparkline (since we don't have enough monthly for that).

**Pull request merged**
