### PR TITLE
Adds how-it-works content and layout for disbursements

### LINKED ISSUE #3227: Expand detail in disbursements documentation
We lack sufficient information about how disbursements are apportioned. For example, we list how much ONRR disbursed to states (and each state), but we don't have documentation about the formula that determines how much a given state receives.

We also lack sufficient documentation describing why and how portions of geothermal revenues are disbursed directly to counties.

We should consider reviewing our documentation and determine where it may lack sufficient information to understand the data.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3227, #3321

[:deer: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/understand-disbursements/how-it-works/#disbursements)

Changes proposed in this pull request:

- Adds section to how-it-works layout dedicated to disbursements
- Creates new supporting content for disbursements

### CODE REVIEW

**Comment by mcharg** [comment]
Here's my feedback:

- You might want to use the word "source" somewhere in the "disbursements and location" section, so users can tie it to that when we use the word "source" elsewhere.
- Will listing out LWCF, HPF, and GOMESA under disbursements make users think those are the only funds we disburse to?

**Comment by jennmalcolm** [comment]
I think this is on the right track. I think it would make more sense to break out onshore, offshore, and Native American all separately. I.e., I would get rid of the "Onshore and offshore" section. Some of that could be used in an intro for the Disbursements and location section, but then I think onshore should have its own section.

**Comment by brentryanjohnson** [comment]
Thank you both, @jennmalcolm and @mcharg. 

@mcharg I thought the same thing about listing those funds' pages, but I'm not sure what else to do with them. We're not going to produce the same level of content for every fund, so we may have to: (1) rely on users understanding the supporting content doesn't include all funds, (2) roll the LWCF, HPF, and GOMESA content under a single disbursements narrative, (3) write basic content for each fund and include it under that section, (4) something I haven't thought of, yet! It's a great point, since it's now conspicuous that we don't have supporting content for the Reclamation Fund (for example).

@jennmalcolm I added a dedicated onshore section and elaborated on the states' portion. Please review again, especially the reference to the 1% of "admin" funds. I couldn't remember exactly how we worded this before.

**Comment by jennmalcolm** [comment]
@brentryanjohnson it looks good to me.

**Comment by mcharg** [comment]
@brentryanjohnson What if we made the"learn how disbursements work" a paragraph instead of just a link and explain there that it explains everything.

Something like this:
**How disbursements work**
Learn about who receives disbursements, the laws governing them, and the impact location has on who gets the money.
_Learn how disbursements work_

We could do the same thing for revenue, if we want to be consistent.

**Comment by brentryanjohnson** [comment]
@mcharg Breaking out those links into the section is a good idea, since those links get lost a bit. I'll try that and see how it works.

**Comment by brentryanjohnson** [comment]
@mcharg and @jennmalcolm I pushed another commit; please have another look!

**Comment by brentryanjohnson** [comment]
@mcharg Testing without the paragraphs, and it looks _much_ cleaner and easier to interact with. I'm going to remove them for now, as you suggested, and we'll rewrite them if it seems useful to connect the dots between the links below each subheading. 👍

**Comment by mentastc** [comment]
@brentryanjohnson  we could add "other to the listed funds. these are payments to federal agencies

image

**Comment by jennmalcolm** [comment]
@brentryanjohnson what do you think about adding the other funds as @mentastc suggested?

**Pull request merged**
