### PR TITLE
Adds glossary filter to search terms to conditionally print term result

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/search-gloss-filter/)

Changes proposed in this pull request:

- Adds filter to only print glossary copy if search term is in glossary

### CODE REVIEW

**Comment by jennmalcolm** [comment]
Did you know this build failed @brentryanjohnson?

**Comment by brentryanjohnson** [comment]
No, @jennmalcolm. I'll take a look.

**Comment by brentryanjohnson** [comment]
I fixed the build problem, @jennmalcolm (the CircleCI failure is separate, related to the unit tests). You should be able to preview now.

There is a one minor problem with a flash of text that I'll try to fix down the road.

**Comment by mcharg** [comment]
@brentryanjohnson Now that we know the term is in the glossary, would it make more sense to say something like "BLM is in our glossary." instead of "you might try searching..." to make it clear we've already done the work and there's no question that it's in the glossary?

**Comment by jennmalcolm** [comment]
This is looking good, and keeps getting better. One last thing that I think would be nice (if there's a method that you could do it easily) is to still print the glossary link for acronyms like NGL and EIS, which are in the glossary as parentheticals with their terms.  I don't think we should use a partial match like the glossary serach does, but perhaps, you could make manual exceptions for these? Here is the list of acronyms that this situation applies to in case you have extra capacity to work on this more when you're dealing with the flash: CY, EIS, FY, IA, MSG, NAICS, NGL, RAC

This is not a must have, so I am going to approve. It is already a big improvement.

**Pull request merged**
