### PR TITLE
3156 add state pages

### LINKED ISSUE #3156: Add state pages to gatsby
Use create pages to automatically generate the state pages

### PR DESCRIPTION
**Pull request by master12**
Fixes #3156 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3156-add-state-pages/)

Changes proposed in this pull request:

- Added all state pages but not offshore areas
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
County maps are broken in IE.  Also, the label above the maps should be "COUNTY PRODUCTION".
image

**Comment by mcharg** [comment]
The ownership map is also broken in IE, but it is in current state, as well.  Can we hide the maps in IE, if they're broken?
image

**Comment by brentryanjohnson** [comment]
I noticed Wyoming (for example) is "Not found":

not found

**Comment by mcharg** [comment]
There also appear to be some copy and paste errors.  For example, Maine has two sections for production in the entire state.  The second one should be for federal land.
image

**Comment by brentryanjohnson** [comment]
Withhelds aren't being handled properly. For example, county maps are being generated for withheld products in this PR for coal and potash in New Mexico.

empty coal county map

empty potash county map

Whereas in prod, withhelds do not generate charts or maps, but are rather listed below the maps.

production maps with withheld problem

**Pull request closed without merging**
