### PR TITLE
Adds accessibility blog post

### LINKED ISSUE #4480: Cowrite blog post with Sam on limitations of automated accessibility testing
Through coworking with an ONRR colleague, we discovered some accessibility obstacles with the website that didn't surface in our automated testing. Once we address them, we should write a blog post about the importance of working with humans to evaluate accessibility issues and opportunities, and not lean too hard on automated testing.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #4480

[✍️ PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/accessibility-blog-post/blog)

Changes proposed in this pull request:

- Adds accessibility blog post in recognition of National Disability Employment Awareness Month

_In WIP because we're waiting for review from ONRR colleague._

### CODE REVIEW

**Comment by jennmalcolm** [comment]
The Lighthouse link give me this
image

**Comment by brentryanjohnson** [comment]
@jennmalcolm That appears to be (1) just in Chrome and (2) just in Chrome on a DOI machine. Oddly, the site _about_ the tool is blocked, but the tool itself can be used via the web inspector in Chrome.

I'm trying to decide if that's a deal breaker. Do you think if it's just a DOI issue, I should still remove the link? I could probably find an alternative link, but it wouldn't represent the same authority of the tool.

**Comment by jennmalcolm** [comment]
@brentryanjohnson, I'd say keep the link if it's just a DOI issue. It will still provide value to the non-DOI readers, and I wouldn't change the link since that's the tool site.

**Comment by brentryanjohnson** [comment]
Sam also approved of the post, so we can move forward with publishing. 👍

**Pull request merged**
