### PR TITLE
"Fixes" double production units on homepage tab

### LINKED ISSUE #4733: Fix duplicate units on production
We have duplicate units on production values on the homepage.

Units for production with duplicate labels, bbl, bbl, mcf, mcf, tons, tons

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #4733

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/double-vision-units/)

Changes proposed in this pull request:

- Fixes duplicate production units

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
This is working for the Fiscal Year/Calendar Year switch, but not for the Yearly/Monthly switch. More to do...

**Comment by brentryanjohnson** [comment]
This should be working now.

**Comment by jennmalcolm** [comment]
Now the units are missing for the monthly charts. Was that the intention?

**Comment by brentryanjohnson** [comment]
Definitely not, @jennmalcolm. They show up for me...I'll check to see if that's just cache.

Production values for oil, gas, and coal by month for a 10-year period with units showing

**Comment by jennmalcolm** [comment]
Ok, Ithe duplicate issue does seem "fixed," but the units above the graphs are missing for monthly. Also, is there a reason that on the live site we spell "barrels" out for yearly graphs and use "bbl" for the monthly graphs. 
image

**Comment by brentryanjohnson** [comment]
Ah, I see @jennmalcolm. I'll look into the missing top labels.

There are two forms for the units, referred to in the code as `longUnits` and `shortUnits`. I'll see if I can work the long units into the top label.

**Comment by brentryanjohnson** [comment]
Okay, @jennmalcolm, I think I've fixed the missing title unit. I'm not sure why it shows long units on one view, and short units on the other, so I can look into that more. Also, I'm not sure that we need the units in three places on this chart, so the title units can probably be omitted (thoughts?).

**Comment by jennmalcolm** [comment]
Yes, the missing units are back now. I don't think it's necessary to have the units in three places, the units with the max dotted line are also inconsistent on the oil graph (barrels with annual and bbl with monthly) I prefer using barrels here for people who may not know the bbl abbreviation. I wonder if it would also make sense to spell out "thousand cubic feet" on the gas line?

**Comment by lpgoldstein** [comment]
@jennmalcolm @brentryanjohnson I think it would make sense to spell out the units as well. Someone recently brought up that she/he didn't understand mcf. I think it was in a user interview.

**Pull request merged**
