### PR TITLE
3540 native american ownership

### LINKED ISSUE #3540: Build Native American ownership & governance page in Gatsby
https://revenuedata.doi.gov/how-it-works/native-american-ownership-governance/

### PR DESCRIPTION
**Pull request by master12**
Fixes #3540 #3501 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3540-native-american-ownership/how-it-works//)

Changes proposed in this pull request:

- Added pages How it works and Native American Ownership
- Added components for displaying data
- Added Page TOC component for menu
- Fixed link issue on how it works default page

### CODE REVIEW

**Comment by jennmalcolm** [comment]
This is looking good to me. One minor thing I noticed on that in the nav menu when I select Indian Mineral Leasing Act if 1938, it doesn't go bold, but Indian Mineral Development Act of 1982 does. The rest seem to be working correctly. 
image

I also noticed the last link on the Native American Ownership page is broken, but it is also broken on the live site, so I will make a quick issue for that.

**Comment by mcharg** [comment]
@jennmalcolm I just beat you to the issue for the link. #3634

**Comment by mcharg** [comment]
On How It Works, the link @brentryanjohnson fixed in #3550 is still broken.

**Comment by mcharg** [comment]
IE layout is wonky.  #3635

**Comment by mcharg** [comment]
#3550 and #3635 are fixed.

**Comment by mcharg** [comment]
#3503 is fixed

**Comment by master12** [comment]
I think all issues have been addressed except for the link 3635

**Comment by brentryanjohnson** [comment]
I confirmed `terms.yml` exists in the branch and contains the entry for `Authorization` that should populate here.

**Comment by master12** [comment]
@brentryanjohnson found the issue with Authorization. Also good catch since it was the only one to have that issue. Mark this one for a unit test.

**Comment by master12** [comment]
Glossary fixed. Please approve and pull this branch before the other how it works stuff since I am branching off of this branch to finish up adding pages

**Comment by mcharg** [comment]
@master12 The glossary is working for me.  @brentryanjohnson is out today, so he won't be approving until Tuesday.

**Pull request merged**
