### PR TITLE
3954 update filterable table

### LINKED ISSUE #3954: Build updated filterable table design
https://t81vx1.axshare.com/#g=1&p=revenue_table_-_stats_plus

Differences from current state:
- Add drop-downs to select land category and location
- Land category rolls up the current land owner and source columns
- "organize by" changes to "first column"
- "add columns" changes to "second column" and users can only add one second column
- Second column that's added is broken out
- Shading on total rows

### PR DESCRIPTION
**Pull request by master12**
Fixes #3954 #3911 

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3954-update-filterable-table/explore/revenue/)

Changes proposed in this pull request:

- Updated table to fix blanks
- Updated table to include grouping
- Updated table to use and apply button
- Updated filterable and group by options

### CODE REVIEW

**Comment by mcharg** [comment]
I've created separate issues for tweaks, but the table isn't showing up at all in IE, Edge, (#3934) and mobile Safari (#4059).  We probably should fix that before releasing.

**Comment by master12** [comment]
@mcharg It appears there is a loading issue with react-dom-min.js file. Refresh your browser a couple times to see if it loads. I will try to see if there is a solution.

**Comment by mcharg** [comment]
@master12 I think the logic around not tied to a location is off.  It's showing up when I picked a single location.
image

**Comment by master12** [comment]
@mcharg oh could catch on location. The data actually pulls from multiple columns for location so I shoudl change that. Need to check all columns or make a single source which is what I think i will do.

**Comment by jennmalcolm** [comment]
@mentastc @Maroyafaied @lpgoldstein could 2 or all of you check some data?

**Comment by Maroyafaied** [comment]
@jennmalcolm yes, I'll review it now.

**Comment by Maroyafaied** [comment]
I'm seeing a difference in numbers for coal for Bonus's  2016 -2018
image
image

**Comment by Maroyafaied** [comment]
Oil & Gas (Non-Royalty) is listed twice under Rents, the first row is accurate but not sure what the other row is pulling. 
image

**Comment by master12** [comment]
@Maroyafaied You also have to include the Native American file. Which has $1 million in 2018 so that is the difference I think you are seeing.

**Comment by master12** [comment]
@Maroyafaied The oil and Gas is from the native american file. there must be an extra space or something. i will get the numebr to merge. thanks

**Comment by lpgoldstein** [comment]
Noticing that a several numbers are slightly off from the current version of the table. Is this normal? 
Example: other revenues 2018: new table $147,193,229 vs $147,193,234 in current table

**Comment by Maroyafaied** [comment]
@master12 the coal numbers are fine after including the Native American file. Also, I'm not seeing offshore inspection fees on the table.

**Comment by Maroyafaied** [comment]
The revenue type "other revenues" does not show when you select a specific state.

**Comment by mentastc** [comment]
Looks like Inspection fees are not included in the filterable table making the bottom line totals off by around 40 million each year
image

**Comment by mentastc** [comment]
Other Revenues not showing up when filtering by State and Revenue Type (also I don't believe that they show up when you're just looking at state)

image

**Comment by master12** [comment]
> Looks like Inspection fees are not included in the filterable table making the bottom line totals off by around 40 million each year
> image

I see inspection fees?

image

**Comment by Maroyafaied** [comment]
The inspection fees show on the general table but don't show when you select an offshore property. The same for other revenues, they show on the general table but not when you select a specific state.

**Comment by jennmalcolm** [comment]
@Maroyafaied and @mentastc where the revenues are not linked to a specific state or onshore/offshore, they will not show up when sorted by that category. In the data, there are no locations linked to inspection fees. 

@master12 any way you could work in the treatment of blanks #3911 so that could be part of this iteration? Since even on our team we have trouble understanding the current treatment of blanks, this will likely be an issue for users without as much experience with the data.

**Comment by master12** [comment]
@jennmalcolm The treatment of blanks is a part of this

**Comment by mcharg** [comment]
@jennmalcolm There's one outstanding item with blanks, which is the cells with no data that are showing up as 0s, which Jeff said was a big fix, so we created #4051 to handle it later.

**Comment by jennmalcolm** [comment]
Ok, @master12 sorry for not seeing that. @Maroyafaied and @mentastc  I don't think that the inspection fees should show up when you select a specific location since they are not tied to a specific location. Let us know if you see any remaining issues with other revenues for locations after Jeff fixed the logic for that.

Thanks, @mcharg that makes sense.

**Comment by mentastc** [comment]
@jennmalcolm  when a sorting field is blank we could have it return that line as "not tied to [field name]" I like this because than our bottom line totals would always be the same.  But I do get the logic at if it doesn't have a location then it won't show up.

**Comment by mcharg** [comment]
@mentastc That's essentially what we're doing with "not tied to a commodity" and "not tied to a location".  The difference is between sorting and filtering.  Sorting shouldn't change the total, but filtering will winnow the data down to just the items that match the filter selections.

**Comment by mcharg** [comment]
I'm okay with approving this, but I can't find the approved button on my phone.  

@master12 There is a layout issue that would be nice to fix noted in a comment on the issue for the Native American note, but it shouldn't hold up release.

**Pull request merged**
