### PR TITLE
new blog

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #<5012>

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/blog_post_0420/)
Changes proposed in this pull request:
-Adds new blog post

### CODE REVIEW

**Comment by jennmalcolm** [comment]
There's an extra paragraph in the middle of a sentence. Also, do you think the revenuedata.doi.gov should be a link?
image

**Comment by jennmalcolm** [comment]
need a space after the blog post link 
image

**Comment by jennmalcolm** [comment]
add a comma before and 
image

**Comment by jennmalcolm** [comment]
probably should use whole name, haven't introduced NRRD acronym
image

**Comment by jennmalcolm** [comment]
You use ONRR acronym later so should include it in parenthesis here. 
image

**Comment by jennmalcolm** [comment]
another extra paragraph break 
image

**Comment by jennmalcolm** [comment]
need another comma before this and 
image

**Comment by jennmalcolm** [comment]
need comma and "to" 
image

**Comment by jennmalcolm** [comment]
add comma after that 
image

**Comment by jennmalcolm** [comment]
I think this should be on-the-job 
image

**Comment by jennmalcolm** [comment]
comma 
image

**Comment by jennmalcolm** [comment]
Looks good besides those minor changes. Sorry I didn't notice some of these in the Google Doc.

**Comment by Maroyafaied** [comment]
This period should be removed 
image

**Pull request merged**
