### PR TITLE
3551 howitworks oil gas

### LINKED ISSUE #3551: Build Offshore Oil & Gas page in Gatsby
https://revenuedata.doi.gov/how-it-works/offshore-oil-gas/

### PR DESCRIPTION
**Pull request by master12**
Fixes #3551

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3551-howitworks-oil-gas/how-it-works/offshore-oil-gas/)

Changes proposed in this pull request:

- Added onshore and offshore oil and gas pages
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 There's no preview link.

**Comment by jennmalcolm** [comment]
@mcharg I edited the link so it works now.

@master12 this looks good to me except that the heading for number 5 is "Decommission and reclaim" and in this branch it's only "Decommission."

**Comment by jennmalcolm** [comment]
@master12, it looks like you added reclaim to the coal page, which is good because it is supposed to be there too, but can you also add it to the oil and gas page?

**Comment by master12** [comment]
updated @jennmalcolm

**Comment by mcharg** [comment]
@master12 On mobile, the current page has the Plan accordion open by default to give the user some content up front.  Can you do that on the Gatsby page?

**Comment by master12** [comment]
@mcharg I can. Can you make a separate ticket and assign to me for this sprint? If there is nothing else for this pr please approve. Thanks.

**Comment by mcharg** [comment]
@master12 Created #3687

**Pull request merged**
