### PR TITLE
Dev--> Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:

- Provided Fiscal Year 2019 disbursement data on GOMESA page and relevant state pages
- Added map anchor link
- Fixed monthly production download link 
- Removed economic impact sections from state pages
- Fixed typo on first blog post

### CODE REVIEW

**Comment by Maroyafaied** [comment]
Not sure if this effects this release but this Gulf of Mexico link does not work on the state pages 
image

**Comment by mcharg** [comment]
@master12 @brentryanjohnson Will the offshore link resolve in the build, since the offshore page isn't fully Gatsby yet?  It's working on the live site and the url looks right.

**Comment by jennmalcolm** [comment]
I think that should resolve in production because the URL looks right. The offshore pages are static right now until we get back to that.

**Comment by mcharg** [comment]
The offshore page link did resolve.

**Pull request merged**
