### PR TITLE
Federal reform content updates

### LINKED ISSUE #2897: Update federal reforms content
[Federal reforms](https://revenuedata.doi.gov/how-it-works/federal-reforms/) is out of date. Let's update it.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #2897

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/reform-updates/how-it-works/federal-reforms/)

Changes proposed in this pull request:

- Normalizes references to Deepwater Horizon (versus "Deep Water Horizon")
- Removes links to specific reports and replaces with link to reports landing page
- Updates content to reflect rollback of disclosure requirements in Dodd-Frank

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@brentryanjohnson  thank for making these changes. We surely need to update this content as it is quite out of date. We will need to make some further clarifications about section 1504 of Dodd Frank. The law you referenced used Congress' authority from the Congressional Review Act to invalidate the SEC's rule to implement Section 1504 of Dodd Frank. Still, I believe, Section 1504 of Dodd Frank is the law. That means that the SEC may be working to re-write the rule to implement the legislation. An additional element to this though is that the House is currently considering and act to actually repeal that section of Dodd Frank from the law (https://www.congress.gov/bill/115th-congress/house-bill/4519/text?q=%7B%22search%22%3A%5B%22Dodd+Frank+1504%22%5D%7D&r=1). Given this, I sent an email to my contact from the SEC to see if they can update me on whether they're still working to re-write the rule. When I get that back, we can re-work the wording in that element of your content update.

**Comment by brentryanjohnson** [comment]
@jennmalcolm I've clarified the language around Section 1504. Please let me know if this accurately conveys the legal disposition of the provision.

I'll take care of the merge conflicts when we're ready to publish.

**Comment by jennmalcolm** [comment]
@brentryanjohnson, could we make a couple more changes? Here is what I suggest:

In early 2017, Congress voted to disapprove an SEC rule implementing Section 1504 of the Dodd-Frank Act. President Trump signed the resolution on February 14, 2017. This resolution prevents the SEC from enforcing Section 1504 of Dodd-Frank until a new rule is published.

Also, I haven't heard from my contact at the SEC yet, but I guess it doesn't matter. I would assume they are still working on a new rule, but we don't need to include that level of detail in our content on Dodd-Frank.

**Comment by brentryanjohnson** [comment]
Great edits, @jennmalcolm. I've incorporated them into the branch.

**Comment by brentryanjohnson** [comment]
We need to edit the content related to Deepwater Horizon regulations given the recent executive order to roll them back, but we can merge these edits and revisit soon.

**Pull request merged**
