### PR TITLE
Updates monthly production and revenue files, 12/2018

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Part of #3479

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/monthly-downloads-12-2018/downloads)

Changes proposed in this pull request:

- Updates monthly production download file (1/2008–8/2018)
- Updates monthly revenue download file (1/2008–11/2018)

### CODE REVIEW

**Comment by Maroyafaied** [comment]
image
should we update the years in this paragraph? data looks good

**Comment by Maroyafaied** [comment]
this one as well for production 
image

**Comment by Maroyafaied** [comment]
sorry also this month. 
image

**Comment by brentryanjohnson** [comment]
@Maroyafaied The annual data is still only through 2017, so I think we should leave that the same. I pulled the years entirely from the downloads landing summary for production, because we'll have a different scope for yearly versus monthly data.

I'm not sure where that "7/2018" issue is coming from. You might need to refresh. The preview should have the updated date.

**Comment by Maroyafaied** [comment]
It shows 8/18 now. and sorry brain fart about the yearly data only being through 2017.

**Comment by brentryanjohnson** [comment]
No worries, @Maroyafaied. Thank you for catching the year ranges on the downloads landing page. I needed to rewrite that summary! :)

**Comment by jennmalcolm** [comment]
@mentastc why do we still have the production date field in this production file?

**Comment by jennmalcolm** [comment]
@brentryanjohnson, there are a few things that need to happen with this PR before merging:

1. The files need to be updated to the most recent
https://github.com/ONRR/doi-extractives-data/files/2829606/Production.Volumes.as.of.02_04_2019.xls
https://github.com/ONRR/doi-extractives-data/files/2829605/monthly_revenue_01-2019.xlsxx

2. I saw a typo in the text changes for the downloads default page
image

3. Production date definition under _downloads/federal-production-by-month.md needs to go away. That is taken out of the file now.

4. The land category definition under production is not right based on the new data format. Use the definitions from the revenue section except you can remove the part about using "Indian" (in both places) because it is reflected as "Native American" in the files now too.  
image

We can do some of this in separate issues if you want, I just didn't want to lose what you had already done in this branch.

**Comment by jennmalcolm** [comment]
Everything looks good now. Thanks @brentryanjohnson.

**Pull request merged**
