### PR TITLE
Blog post: Making tough content choices

### LINKED ISSUE #3896: Write blog post about making tough content choices
I'm scoping a blog post about making tough content choices (not _how_ to make tough content choices, although there will be hints of that). 

Some ideas:

- weighing content and workflow variables
- team size and composition
- if you can't do it _well_, then you probably shouldn't do it
- it may be valuable, but not maintainable (and can it be justified in that context)

...

More to come.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #3896

[:pencil: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/blog-content-choices/blog)

Changes proposed in this pull request:

- Adds blog post about making tough content decisions

### CODE REVIEW

**Comment by mcharg** [comment]
Found a typo. 
image

**Comment by brentryanjohnson** [comment]
Thank you, @mcharg. Fixed in this commit. ☝️

**Comment by mcharg** [comment]
image

**Comment by mcharg** [comment]
image
In the paragraph below, you end up saying that content design **is** user-centered design, so maybe it would be better to reframe the section as balancing user needs and content needs instead of saying that user-centered design is limited.

**Comment by brentryanjohnson** [comment]
Good point, @mcharg. What do you think of this alternative?

## Understanding your constraints _is_ user-centered design

**Comment by mcharg** [comment]
I like it! @brentryanjohnson

**Comment by usEITI** [comment]
I like it too.

**Comment by jennmalcolm** [comment]
Do you want to say "group" here?
image

**Comment by jennmalcolm** [comment]
Do you want "unavoidable"?

image

**Comment by jennmalcolm** [comment]
It's very good. I enjoyed the read and your points!

**Pull request merged**
