### PR TITLE
October 2019 disbursements

### LINKED ISSUE #4830: October 2019 Disbursements Download
Add October 2019 disbursements download files

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #4830

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/disbursements-october-2019/)

Changes proposed in this pull request:

- updates disbursements download files
- updates file size on disbursements download pages
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
FY19 needs to be changed to FY20 @master12 @mojobnichols  would you please change when you have time? 
image

**Comment by Maroyafaied** [comment]
@lpgoldstein @master12  are these numbers supposed to just be October 2019 data for FY20.? I think it's pulling all of FY19 data and the month of Oct 2019 numbers.

**Comment by lpgoldstein** [comment]
Sorry realized that I responded in Slack 
@Maroya Faied they are supposed to be just the fy20 data if we want them to be the same as the revenue trends numbers. So they aren't pulling correctly @mojo could you please take a look at that too?

**Comment by mojobnichols** [comment]
I got this fixed yesterday.  I added fiscal year with logic similar to revenue transform.   I noted that I am not limiting the lower year of trend line.   I assume we would like me to only go back 10 years like revenue?   I would like confirmation before doing that.

**Comment by mojobnichols** [comment]
> I got this fixed yesterday. I added fiscal year with logic similar to revenue transform. I noted that I am not limiting the lower year of trend line. I assume we would like me to only go back 10 years like revenue? I would like confirmation before doing that.

I just set it to last 10 years as that is what is desired I believe.

**Comment by mojobnichols** [comment]
Should work now with % differences

**Comment by mojobnichols** [comment]
well in 30 minutes or so

**Comment by lpgoldstein** [comment]
@mojobnichols Thank you. The numbers for FY20 look good but the percentage change vs Oct 2018 are off. How are those being calculated?

**Comment by mojobnichols** [comment]
Yeah it wasn't doing year to fiscal month it was doing previous year,  I've corrected that so  hopefully now it will work.

**Comment by jennmalcolm** [comment]
@brentryanjohnson I think it was just the funds receiving the most money and trying to fit into the space we have. We could probably fit a line for LWCF on there too now, or do you have alternate suggestions?

**Comment by brentryanjohnson** [comment]
It creates a tricky problem @jennmalcolm, because it implies an "importance" or relevance hierarchy to show some or one fund and roll up the others. I suppose it could be argued that average users might care about LWCF more the Reclamation, but it would be equally odd, in some ways, to only show LWCF here.

I think we should discuss it more, and figure out our strategy for that section.

**Comment by jennmalcolm** [comment]
Ok, I created #3858 for that @brentryanjohnson

**Pull request merged**
