### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:
- Adds accessibility blog
- Updates monthly production through June 2019
- Updates monthly and annual disbursements through Sep 2019/FY19
- Updates monthly and annual revenues through Sep 2019/FY19
- Addresses accessibility errors
- Adds Federal - not tied to lease to homepage revenue chart
- Fixed totals inconsistencies due to rounding
- Updated LWCF content
- Other minor updates

Places to check data:
Production Monthly (monthly_production)	
- [ ] Homepage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Hompage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Fiscal Year (fiscal_year_revenue)	
- [x] Homepage: FY bar charts
- [x] How it works: Native American revenue table 
- [x] Explore data: Filterable revenue data table 
- [x] Download: xls and csv files updated with correct dates and file size

Disbursements Monthly (monthly_disbursements) 	
- [x] Homepage: disbursements trends
- [x] Download: xls and csv files updated with correct dates and file size

Disbursements Fiscal Year (disbursements)	
- [ ] Homepage: FY bar chart
- [ ] Explore data: by recipient table
- [ ] Download: xls and csv files updated with correct dates and file size"
- [ ] State page disbursements

### CODE REVIEW

**Comment by jennmalcolm** [comment]
The disbursements updates aren't in dev yet so begin reviewing everything else and hopefuly we'll get those figured out soon.

**Comment by jennmalcolm** [comment]
The disbursements monthly xls and csv and FY csv only updates are now in dev and can be checked. We are still having trouble with the build for the xls disbrusements update.

**Comment by mcharg** [comment]
The disbursements files you said were updated have the right dates in them.

**Comment by lpgoldstein** [comment]
double volume measurements on production homepage monthly bar charts
image

**Comment by jennmalcolm** [comment]
I think we will do a release around noon with what we have and keep working the disbursements issues this afternoon. Please approve this PR if you don't find any issues aside from the know disbursements ones. @lpgoldstein there is an issue #4733 for the duplicate units showing up.

**Pull request merged**
