### PR TITLE
Added a DispersementTrends module to Dispersement tab

### LINKED ISSUE #4388: Build disbursements trends
https://sjzq35.axshare.com/#g=1&p=alt_tab_styling

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #4388 
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/438*-DisbursmentTrends/)

Changes proposed in this pull request:

WIP pending other new home page components being finished. 
Distribution trends chart for distribution tab.

noted in demo add monthly data and  remove percent change if not enough monthly data. 

-
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/onrr/doi-extractives-data/4388-DisbursmentTrends/)

**Comment by mcharg** [comment]
There are a bunch of things that need to be done to clean this up (some we talked about in demo, but I thought it would be helpful to have them listed in one place):
- [ ] Change title of the section from "Distribution trends" to "Disbursements trends"
- [ ] Change intro copy to "Includes disbursements through [most current month][year]"
- [ ] Use monthly data for the FY19 so far column
- [ ] Hide the % change and arrows until we get to FY20
- [ ] Figure out if there's a way to use both yearly and monthly data in the trend line, so we use yearly through FY18 and monthly from FY19 forward
- [ ] Remove the line over the total row, so we're consistent with revenue trends

@jennmalcolm Where we're going to have more vertical space on the new homepage, should we split out LWCF and HPF, so Other funds is consistent with the disbursements summary on Explore data?

**Comment by mojobnichols** [comment]
Thanks for the checklist.   As I have created the blocking issue for the monthly not being in graphql I'm going to hold off on the following, once I have month I will make the the percent change based on month and then make it smart enough to not show up if you don't have previous month, so it will work automatically once we have appropriate data.  

 * [ ]  Change intro copy to "Includes disbursements through [most current month][year]"
 * [ ]  Use monthly data for the FY19 so far column
 * [ ]  Hide the % change and arrows until we get to FY20

A thought for the following is to end the chart in the monthly data in orange, so that the orange chart reflects the percent change above. 

 * [ ]  Figure out if there's a way to use both yearly and monthly data in the trend line, so we use yearly through FY18 and monthly from FY19 forward

**Comment by mcharg** [comment]
@mojobnichols Re ending the chart the the monthly data in orange, that was something we wanted to do for the revenue trends (highlighting the current FY), but @brentryanjohnson needed help figuring out how to do it.  I think that could also work well for disbursements.

**Comment by mojobnichols** [comment]
I'm think this is a new issue, but I have some thoughts so I want to put them down before leaving for the weekend.

if % change is  cumulative YTD June 2019  vs cumulative YTD June 2018 then:

plot 2008 ... 2018 yearly data.  
let expansion be  2018 yearly data / YTD June 2018
change sparkline color
plot 2019 YTD * expansion  

Now the orange part of graph represents the percent change ytd relative to last years total change. ... maybe

if % change is just June to June do the same thing except  use june months instead of cumulative.

**Comment by jennmalcolm** [comment]
Closing since this is in #4174 now

**Pull request closed without merging**
