### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by jennmalcolm**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/)

Changes proposed in this pull request:
- Updated monthly production through Sep 2019
- Updated monthly disbursements through Nov 2019
- Updated monthly revenue through Dec 2019
- Changed source data for homepage FY production and revenue graphs to monthly files
- Changes CY graphs to require full year of data
- Added source data links to home page
- Updated content and fixed errors noted in content audit
- Added code to allow for URLs based on query data filters
- Other minor fixes

Data to check:
Production Monthly (monthly_production)	
- [x] Homepage: monthly bar charts
- [x] Homepage: CY bar charts
- [x] Homepage: FY bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Revenue Monthly (monthly_revenue)	
- [x] Homepage: revenue trends charts
- [x] Homepage: CY bar charts
- [x] Homepage: FY bar charts
- [x] Hompage: monthly bar charts
- [x] Download: xls and csv files updated with correct dates and file size

Disbursements Monthly (monthly_disbursements) 	
- [x] Homepage: disbursements trends
- [x] Download: xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@jennmalcolm it's duplicating the units for production fiscal year homepage charts
image

**Comment by Maroyafaied** [comment]
@jennmalcolm Also for production CY homepage charts it's not showing CY 2019
image

**Comment by jennmalcolm** [comment]
@brentryanjohnson fixed the duplicate units issue once before. Can you help us fix it again @brentryanjohnson?

**Comment by jennmalcolm** [comment]
@Maroyafaied we do not want CY19 to show up until we have a full year of data.

**Comment by brentryanjohnson** [comment]
> @brentryanjohnson fixed the duplicate units issue once before. Can you help us fix it again @brentryanjohnson? It's only appearing on fiscal year.

My "fix" was a more of a hack, which apparently was reverted later. It might be a longer-term fix if @master12 handles it this time.

**Pull request merged**
