### PR TITLE
Replaces homepage world ranking text with vision-derived statement

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:pencil: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/context-statement/#context-cards)

Changes proposed in this pull request:

- Replaces "world ranking" sentence on homepage
  - U.S. world ranking for coal is possibly out of date (some data sources list the U.S. third globally, not second)
  - The updated site vision is focused on how the federal government manages extraction on federal land, not how the U.S. ranks globally for all extractives production

### CODE REVIEW

**Comment by jennmalcolm** [comment]
I like it @brentryanjohnson. Since you have me on as an asignee, I don't know if you're ready for me to approve and merge it. Let me know.

**Comment by brentryanjohnson** [comment]
Apologies, @jennmalcolm. I intended to mark you as reviewer, not assigned!

**Comment by Maroyafaied** [comment]
I thought we changed this message @brentryanjohnson? I just saw it on the website and it's still the same

image

**Comment by jennmalcolm** [comment]
@Maroyafaied the change will go live to the site when we do our next release. Even after we merge to dev, there are a couple more steps before the changes get to the live site. I think our meeting Thursday should help explain this a bit more.

**Comment by Maroyafaied** [comment]
@jennmalcolm I see, thanks for explaining.

**Pull request merged**
