### PR TITLE
3192 key stats feature

### LINKED ISSUE #3192: Build key facts section on pattern library
See #3146 for detailed design

### PR DESCRIPTION
**Pull request by master12**
Fixes #3192

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3192-key-stats-feature/patterns/components/keystatssection/)

Changes proposed in this pull request:

Added the following ot the pattern library to complete the key stats section
- ChartLegendStandard
- ChartTitle
- Toggle
- Accordion
- StackedBarChart
- StackedBarChartLayout
- ExploreDataLink
- KeyStatsSection
- Also started implementing css modules for all components

### CODE REVIEW

**Comment by mcharg** [comment]
ChartLegendStandard
- The color swatches are still not horizontally aligned with the labels

ChartTitle
- No issues

Toggle
- No issues

Accordion
- No issues

Stacked bar chart
 - No issues

Stacked bar chart layout
- The coloring in the legend and bars is off.  The color that displays on the bottom of the chart should be first in the legend and the one in the top of the bar should be last in the legend.  Offshore and GOMESA colors are backwards in the bar on the example.
- The line at the top that shows the scale of the chart is missing.

Explore Data link
- Looks good

Key stats section
- The drop-down to pick the period for monthly data is missing
- When we get to the two column view, all the charts should be the same width.  The production ones are narrower than revenue and disbursements here.
image

**Comment by mcharg** [comment]
@brentryanjohnson You are correct about the interactivity.

On the disbursements and revenue charts, I played with the charts aligning, but I think that will make a weird space for disbursements when we get to the one column view, unless we can only have the padding when in the 2 column view.

**Comment by mcharg** [comment]
@brentryanjohnson What are your thoughts on just using a single letter for the month names if we can't get them to fit with the 3 letter names?

**Comment by brentryanjohnson** [comment]
@mcharg The extra spacing can be removed at the breakpoint via a media query, so it shouldn't affect the one-column layout.

**Comment by brentryanjohnson** [comment]
@mcharg It's not ideal (to only include one letter for the month), but I think it might be the only way to properly label them without them running together. We should probably try that and see how it performs.

**Comment by master12** [comment]
We can just make the chart wider.

**Comment by mcharg** [comment]
@master12 How wide can we make it and still fit 3 across?  We also need to make sure there's enough space between them to have visual separation between the charts.

Here are the specs from the prototype (Production section).
Chart: 284 px
Space between: 42 px
Font for month names: 13 pt lato light

**Comment by mcharg** [comment]
Bars: 15 px wide

**Comment by mcharg** [comment]
The other thing that's missing is the year labels below the months.

**Comment by mcharg** [comment]
Colors

Selected:
Darkest: #086996
Medium: #79BBDA
Lightest: #C6E9FF

Hover:
Selected color with 80% opacity

Unselected:
Darkest: #4E4E4E
Medium: #A9A9A9
Lightest: #E0E0E0

**Comment by mcharg** [comment]
@master12 One other thing to note when you build the hover functionality in the table below, is that the key colors should change to the hover colors when showing the numbers for the year that is hovered over.

**Comment by master12** [comment]
I am canceling this pull request in favor of creating a new PR for the home page which this feature will be added.

**Pull request closed without merging**
