### PR TITLE
FY Production Update

### LINKED ISSUE #4976: 2019 FY Production Data Set
Update FY production data set 
-verify data
-update downloads

### PR DESCRIPTION
**Pull request by mentastc**
Fixes #4976 

[:sunglasses: PREVIEW](https://federalist-64b3729c-c105-408b-a052-d8b049efc23f.app.cloud.gov/preview/onrr/doi-extractives-data/fy-production/)

Changes proposed in this pull request:

- Removes withheld text from downloads page
-Updates download files
-Updates production query tool 

@master12  you will likely need to do some work to make this data set update the query tool, the offshore planning area column was removed.

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mentastc the link is not working for me

**Comment by jennmalcolm** [comment]
@mentastc did you know the build failed on this?

**Comment by jennmalcolm** [comment]
Oh, I guess that was due to the issue with no offshore planning area. @master12 can you take a look?

**Comment by Maroyafaied** [comment]
@master12 @jennmalcolm this link is not working, this is what happens when I click it. 
image

**Comment by jennmalcolm** [comment]
This is looking good. Thanks @master12. @lpgoldstein could you also review the data:

- [ ] Download: xls and csv files updated with correct dates and file size
- [ ] Explore data: Filterable production data table

**Pull request merged**
