### PR TITLE
Updates company revenue (UDR) data to 2017

### LINKED ISSUE #2804: Update federal revenue by company data to 2017
We have [2016 federal revenue by company data](https://revenuedata.doi.gov/how-it-works/federal-revenue-by-company/2016/). We should update this data to 2017.

#2805 covers moving this data out of [How it works](https://revenuedata.doi.gov/how-it-works/#revenues) to an explore data section.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #2804 and #3047

[:bird: How it works - revenue PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/company-revenue/how-it-works/#revenues)

[:dollar: Federal revenue by company, 2017 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/company-revenue/how-it-works/federal-revenue-by-company/2017/)

[:open_file_folder: Data download, revenue by company PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/company-revenue/downloads/federal-revenue-by-company/)

Changes proposed in this pull request:

- Adds federal revenue by company for 2017
- Adds download file for federal revenue by company, 2013-2017
- Updates links, redirects, file paths, and references for federal revenue by company

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@jennmalcolm The redirect is caused by the link going to the generic `federal-revenue-by-company`. There isn't a page there. since the federal revenue by company data is structured by year.

I can avoid the redirect by linking directly to `federal-revenue-by-company/2017/`; we'll just need to update those links every year when we update the data. The redirect allows us to update the link in one place (the redirect), instead of each link. But we still need to remember to update it there.

**Comment by jennmalcolm** [comment]
Ok, if it's easier to update when we keep it like this, that's fine.

**Comment by brentryanjohnson** [comment]
@jennmalcolm Perhaps we can make the links less disruptive when we migrate to the explore data page. That flash isn't ideal.

**Comment by mentastc** [comment]
In doing my review I'm noticing some small revenue numbers and I believe everything under 100k is supposed to be rolled up, I asked Data retrieval to take a look, sorry I didn't catch this in my earlier data review.  I'll keep you posted for what they say.

**Comment by brentryanjohnson** [comment]
I wondered about that, @mentastc, because there is a row titled: COMPANIES BELOW $100,000 THRESHOLD. At first, I thought the intention was to roll up under that threshold, but it certainly shows listings for companies with volumes that are less than that (for 2016, too). 

There is also this also a row for ONE PRODUCT AND ONE MINE (TOTAL OF WITHHELD), but there appear to be listings for companies that may meet this category, too. I do think these rows are supposed to be the rollups, and they are sorted according to amount, like the others.

_"Subheading" is in quotes because these titles are styled and appear the same as the companies themselves, which is confusing in its own right._

**Comment by mentastc** [comment]
Here's DR's response... I told them rolling to oil and gas for the below 100k would be fine.

Hi Chris,

I just spoke to Andrew and we figured out what happened with the UDR as far as the "under $100,000 threshhold".  When Nathan and I fixed the file a couple of weeks ago, we didn't do the step to roll the revenue up.  Andrew is fixing that now.  As far as the Oil, Gas, and Oil & Gas issue, it would be easier and faster to roll the past years up to "Oil and Gas" than to break 2017 into "Oil" and "Gas".  Would it be ok to change the past years or would you prefer to keep the past years the way they are?

**Comment by brentryanjohnson** [comment]
@mentastc I think rolling up to oil & gas is fine, since they're so closely related, and the emphasis is on the companies more than the commodities. As far as past years, oil & gas are split out, so if we want the numbers to be comparable year on year, we may want to consider updating those, too. Perhaps we can talk more about that at standup.

**Comment by mentastc** [comment]
@jennmalcolm  Not yet.

**Comment by brentryanjohnson** [comment]
@mentastc I've update the data file(s) with the roll-ups. Please review and make sure all looks correct.

**Comment by mentastc** [comment]
Looks good to me thanks!

**Comment by brentryanjohnson** [comment]
@master12 When this finishes building, will you give it a quick review on technical merits and merge if all looks good?

**Pull request merged**
