### PR TITLE
3402 fix sticky header

### LINKED ISSUE #3402: Fix sticky header
The sticky header is misbehaving on both my phones. It's not sticking to the top of the page and subheaders are partially covering up the state header.
image

image

### PR DESCRIPTION
**Pull request by master12**
Fixes #3402 #3241

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3402-fix-sticky-header/)

Changes proposed in this pull request:

- mobile sticky header
- redundant menu gone
-

### CODE REVIEW

**Comment by mcharg** [comment]
The sticky header is fixed on the state page, but now it's got the gap on the Explore Data page on my iPhone.
img_9856

The redundant menu is also still showing up at the bottom of both the state and explore data pages.

**Comment by master12** [comment]
Please make new issue. An approve the change that this fix made.

**Comment by mcharg** [comment]
@master12 It only fixed the first bullet that you said this fixed.   The second one is still an issue.  The redundant menu is still there.

**Comment by master12** [comment]
I only looked at the state page. Can we just create a separate issue for the explore data page and approve this one as is for the state page

**Comment by mcharg** [comment]
It's not fixed on the state page.  If you take off the bullet about fixing the redundant nav, I can approve.

**Comment by mcharg** [comment]
Only #2402 is fixed by this PR.  #3241 is still an issue.

**Comment by master12** [comment]
@mcharg menu removed from both explore and state

**Comment by mcharg** [comment]
@master12 Looks good.

**Comment by brentryanjohnson** [comment]
Sticky header appears fixed on mobile for state pages, but some states (e.g., Idaho) redirect to the homepage. I'll create a new issue for that. @master12 @mcharg

**Pull request merged**
