### PR TITLE
[WIP] Adds pattern library documentation

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/patterns-content/patterns/)

Changes proposed in this pull request:

- This is a WIP pull request for adding documentation content to pattern library

### CODE REVIEW

**Comment by mcharg** [comment]
Still getting a 404 error on the preview link.

**Comment by master12** [comment]
this is fixed

**Comment by mcharg** [comment]
I'm still getting the 404 error. 

image

**Comment by master12** [comment]
clear you browser cache

**Comment by master12** [comment]
sorry he has the worng link in the preview:

https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/patterns-content/patterns/

**Comment by mcharg** [comment]
That works!

**Pull request merged**
